import Head from 'next/head'
import { useState } from 'react'

const M = {
  "vendeuse": { t: "Vendeuse / Vendeur", s: "Commerce et vente", d: "Vous postulez comme vendeuse ou vendeur ? Notre IA genere une lettre de motivation personnalisee qui met en valeur votre sens du contact client et votre dynamisme.", c: "Mettez en avant votre aisance relationnelle, votre connaissance des produits et votre capacite a atteindre les objectifs de vente.", ex: "Vendeuse en pret-a-porter, vendeur en magasin, conseiller de vente, vendeur en boulangerie, vendeuse en parfumerie", phrases: ["Mon experience de 2 ans en vente m'a appris a identifier rapidement les besoins des clients.", "Ma connaissance approfondie des techniques de merchandising me permet d'optimiser les ventes.", "Mon dynamisme et mon sens du contact font de moi une vendeuse efficace et appreciee."], faq: [["Faut-il mentionner son chiffre d'affaires ?", "Oui, si vous avez des resultats chiffres, mentionnez-les. Les recruteurs adorent les preuves concretes."], ["Quelle longueur pour une lettre vendeuse ?", "250 a 350 mots suffisent. Soyez concis et percutant, comme en vente."], ["Comment se demarquer sans experience ?", "Mettez en avant vos qualites relationnelles, un job etudiant ou du benevolat impliquant du contact client."]], temoignage: { nom: "Sarah K.", poste: "Embauchee chez Zara", texte: "J'ai genere ma lettre en 30 secondes et j'ai ete appelee pour un entretien 2 jours apres !" } },
  "stage": { t: "Stage", s: "Formation et insertion", d: "Vous cherchez un stage ? Notre IA redige une lettre de motivation qui valorise votre formation, votre motivation et vos competences.", c: "Insistez sur votre envie d'apprendre, vos projets scolaires pertinents et ce que vous pouvez apporter a l'entreprise.", ex: "Stage de 3eme, stage BTS, stage licence, stage master, stage de fin d'etudes", phrases: ["Actuellement en [formation], je recherche un stage de [duree] pour mettre en pratique mes connaissances.", "Mon projet professionnel s'oriente vers [domaine], c'est pourquoi votre entreprise m'interesse particulierement.", "Rigoureux et motive, je souhaite contribuer activement a vos projets."], faq: [["Comment ecrire une lettre de stage sans experience ?", "Focalisez-vous sur votre formation, vos projets scolaires et votre motivation. C'est ce que les recruteurs attendent d'un stagiaire."], ["Quelle longueur pour une lettre de stage ?", "150 a 250 mots. Les recruteurs de stagiaires lisent vite, allez a l'essentiel."], ["Faut-il personnaliser pour chaque entreprise ?", "Absolument ! Mentionnez le nom de l'entreprise et expliquez pourquoi elle vous interesse specifiquement."]], temoignage: { nom: "Lucas M.", poste: "Stage chez L'Oreal", texte: "Ma lettre generee par l'IA etait tellement bien ecrite que mon maitre de stage l'a complimentee !" } },
  "alternance": { t: "Alternance", s: "Formation en entreprise", d: "Vous postulez en alternance ? Notre IA cree une lettre qui montre votre double competence : formation theorique et motivation pour l'entreprise.", c: "Expliquez clairement votre rythme d'alternance, votre formation et pourquoi cette entreprise vous interesse.", ex: "Alternance BTS MCO, alternance licence pro, alternance master, contrat d'apprentissage", phrases: ["En preparation de mon [diplome], je recherche une alternance au rythme de [rythme].", "L'alternance represente pour moi l'opportunite ideale de combiner theorie et pratique.", "Operationnel des ma prise de poste, je m'investirai pleinement dans vos projets."], faq: [["Faut-il preciser le rythme d'alternance ?", "Oui, c'est essentiel. L'entreprise doit savoir quand vous serez present."], ["Comment convaincre sans experience ?", "Votre formation est votre force. Montrez que vous apportez des connaissances fraiches et actuelles."], ["Lettre pour l'ecole ou l'entreprise ?", "Les deux ! Notre IA adapte la lettre selon le destinataire."]], temoignage: { nom: "Emma R.", poste: "Alternance BTS MCO", texte: "3 candidatures envoyees avec la lettre IA, 2 entretiens obtenus. Je recommande a 100% !" } },
  "infirmiere": { t: "Infirmiere / Infirmier", s: "Sante et medical", d: "Vous postulez comme infirmiere ou infirmier ? Notre IA genere une lettre professionnelle adaptee au secteur medical.", c: "Valorisez vos stages hospitaliers, votre empathie, votre rigueur et votre capacite a travailler en equipe.", ex: "Infirmiere en hopital, infirmier liberal, infirmiere en EHPAD, infirmier en bloc operatoire", phrases: ["Diplomee d'Etat depuis [annee], j'ai developpe une expertise en soins [specialite].", "Ma rigueur et mon empathie me permettent d'accompagner les patients avec professionnalisme.", "Mon experience en equipe pluridisciplinaire est un atout pour votre etablissement."], faq: [["Faut-il mentionner ses stages ?", "Oui, detaillez vos stages hospitaliers et les services dans lesquels vous avez travaille."], ["Comment se demarquer dans le medical ?", "Mentionnez vos specialites, formations complementaires et votre approche du soin."], ["Lettre manuscrite ou numerique ?", "En 2025, la lettre numerique est la norme, meme dans le medical."]], temoignage: { nom: "Julie P.", poste: "Infirmiere au CHU", texte: "La lettre etait parfaitement adaptee au monde hospitalier. J'ai ete recrutee en CDI !" } },
  "sans-experience": { t: "Sans experience", s: "Premier emploi", d: "Pas d'experience ? Pas de probleme. Notre IA redige une lettre convaincante qui met en avant vos qualites et votre potentiel.", c: "Concentrez-vous sur vos qualites personnelles, vos activites extra-scolaires et vos projets personnels.", ex: "Premier emploi, job etudiant, candidature sans experience, debutant, jeune diplome", phrases: ["Bien que debutant, ma determination et ma capacite d'apprentissage rapide sont mes meilleurs atouts.", "Mon parcours m'a permis de developper des qualites essentielles : rigueur, ponctualite et esprit d'equipe.", "Je suis convaincu que ma motivation compensera largement mon manque d'experience."], faq: [["Comment postuler sans aucune experience ?", "Mettez en avant vos etudes, vos qualites humaines, votre benevolat ou vos activites extra-scolaires."], ["Les recruteurs acceptent-ils les debutants ?", "Oui ! De nombreux postes sont ouverts aux debutants, surtout dans le commerce, la restauration et les services."], ["Faut-il mentionner ses loisirs ?", "Si vos loisirs demontrent des qualites utiles pour le poste, oui."]], temoignage: { nom: "Amine B.", poste: "Premier emploi en logistique", texte: "Sans experience, j'avais du mal a ecrire. L'IA a su mettre en valeur mes qualites et j'ai decroche le poste !" } },
  "reconversion": { t: "Reconversion professionnelle", s: "Changement de carriere", d: "Vous changez de carriere ? Notre IA cree une lettre qui transforme votre reconversion en atout.", c: "Expliquez votre motivation pour ce changement et les competences transferables de votre ancien metier.", ex: "Reconversion apres licenciement, changement de secteur, retour a l'emploi, nouvelle carriere", phrases: ["Apres [X] annees dans [ancien secteur], j'ai choisi de me reconvertir vers [nouveau secteur].", "Les competences acquises dans mon precedent poste sont directement transferables a ce nouveau role.", "Ma reconversion est le fruit d'une reflexion murie et d'une formation adaptee."], faq: [["Comment expliquer sa reconversion ?", "Soyez positif : parlez de ce qui vous attire dans le nouveau metier, pas de ce qui vous a fait fuir l'ancien."], ["Faut-il mentionner sa formation de reconversion ?", "Oui, c'est essentiel pour prouver votre serieux et votre preparation."], ["Les recruteurs voient-ils la reconversion positivement ?", "De plus en plus ! La reconversion montre du courage, de l'adaptabilite et une forte motivation."]], temoignage: { nom: "Nathalie D.", poste: "De comptable a educatrice", texte: "L'IA a su expliquer ma reconversion de maniere positive. Le recruteur a ete conquis par ma lettre !" } },
  "aide-soignante": { t: "Aide-soignante / Aide-soignant", s: "Sante et medical", d: "Vous postulez comme aide-soignante ? Notre IA redige une lettre adaptee au secteur du soin.", c: "Mettez en avant votre formation DEAS, vos stages, votre patience et votre bienveillance.", ex: "Aide-soignante en EHPAD, aide-soignant en hopital, aide-soignante a domicile", phrases: ["Titulaire du DEAS, j'ai acquis une solide experience aupres des personnes agees.", "Ma bienveillance et mon ecoute me permettent d'etablir une relation de confiance avec les patients.", "Je maitrise les gestes de soins quotidiens et les protocoles d'hygiene."], faq: [["Le DEAS est-il obligatoire ?", "Oui, le Diplome d'Etat d'Aide-Soignant est requis pour exercer. Mentionnez-le en priorite."], ["Comment se demarquer dans ce secteur ?", "Parlez de vos stages, de votre approche humaine et de votre capacite a travailler en equipe."], ["Faut-il une lettre longue ?", "Non, 200 a 300 mots suffisent. Le secteur medical prefere les lettres directes."]], temoignage: { nom: "Fatima A.", poste: "Aide-soignante en EHPAD", texte: "Lettre parfaitement adaptee au monde du soin. Recrutee en 1 semaine !" } },
  "commercial": { t: "Commercial(e)", s: "Vente et business", d: "Vous postulez comme commercial ? Notre IA genere une lettre percutante qui met en avant vos resultats.", c: "Chiffrez vos resultats : CA genere, clients signes, objectifs depasses. Les recruteurs veulent des preuves.", ex: "Commercial terrain, commercial sedentaire, technico-commercial, commercial B2B", phrases: ["En 3 ans, j'ai developpe un portefeuille de [X] clients et genere [X]k euros de CA.", "Ma capacite a identifier les besoins clients et a proposer des solutions adaptees est mon principal atout.", "Oriente resultats, je depasse regulierement mes objectifs de [X]%."], faq: [["Faut-il chiffrer ses resultats ?", "Absolument ! Un commercial sans chiffres, c'est comme un CV sans experience. Donnez des preuves concretes."], ["Lettre courte ou longue pour un poste commercial ?", "Courte et percutante, comme un bon pitch de vente. 250 mots maximum."], ["Comment postuler sans experience commerciale ?", "Mettez en avant toute experience de vente, meme informelle, et votre goat du challenge."]], temoignage: { nom: "Thomas L.", poste: "Commercial B2B", texte: "La lettre a mis en valeur mes chiffres de maniere percutante. Entretien obtenu le lendemain !" } },
  "job-ete": { t: "Job d'ete", s: "Emploi saisonnier", d: "Vous cherchez un job d'ete ? Notre IA cree une lettre courte et efficace pour les emplois saisonniers.", c: "Soyez direct : indiquez vos disponibilites, votre motivation et votre capacite a etre operationnel rapidement.", ex: "Serveur, caissier, animateur, vendeur saisonnier, employe de plage", phrases: ["Disponible du [date] au [date], je suis motive et operationnel immediatement.", "Mon experience en [domaine] me permet d'etre autonome des les premiers jours.", "Dynamique et ponctuel, je m'adapte rapidement a tout environnement de travail."], faq: [["Quand postuler pour un job d'ete ?", "Des mars-avril ! Les recruteurs anticipent leurs besoins estivaux."], ["Faut-il une vraie lettre pour un job d'ete ?", "Oui ! Une lettre bien ecrite vous demarque des centaines de candidats qui envoient juste un CV."], ["Comment postuler a 16 ans ?", "C'est possible avec une autorisation parentale. Mettez en avant votre motivation et votre maturite."]], temoignage: { nom: "Lea S.", poste: "Job d'ete en restaurant", texte: "J'ai envoye 10 candidatures avec la lettre IA, 4 reponses positives. Top pour un job d'ete !" } },
  "candidature-spontanee": { t: "Candidature spontanee", s: "Tous secteurs", d: "Vous envoyez une candidature spontanee ? Notre IA redige une lettre qui capte l'attention meme sans offre.", c: "Montrez que vous connaissez l'entreprise et expliquez ce que vous pouvez lui apporter.", ex: "Candidature spontanee grande entreprise, PME, start-up, prospection emploi", phrases: ["Votre entreprise m'inspire par [raison precise], c'est pourquoi je me permets de vous ecrire.", "Mes competences en [domaine] pourraient contribuer a [objectif de l'entreprise].", "Je serais ravi d'echanger avec vous sur les opportunites au sein de votre equipe."], faq: [["Les candidatures spontanees marchent-elles ?", "Oui ! 70% des postes ne sont jamais publies. La candidature spontanee accede au marche cache de l'emploi."], ["Comment trouver le bon interlocuteur ?", "Cherchez sur LinkedIn le responsable RH ou le manager du service vise."], ["Faut-il relancer ?", "Oui, relancez 7 a 10 jours apres l'envoi. Cela montre votre motivation."]], temoignage: { nom: "Marc V.", poste: "Embauche chez Decathlon", texte: "Ma candidature spontanee a ete remarquee grace a la qualite de la lettre. Merci l'IA !" } },
  "serveur": { t: "Serveur / Serveuse", s: "Restauration", d: "Vous postulez comme serveur ou serveuse ? Notre IA genere une lettre qui met en valeur votre sens du service.", c: "La restauration recrute massivement. Mettez en avant votre resistance au stress et votre polyvalence.", ex: "Serveur en restaurant, serveuse en brasserie, barman, serveur en hotel", phrases: ["Mon sourire et mon sens du service garantissent une experience client de qualite.", "Habitue au rythme soutenu de la restauration, je reste efficace meme en periode de rush.", "Ma connaissance des vins et des plats me permet de conseiller les clients avec pertinence."], faq: [["Faut-il de l'experience pour etre serveur ?", "Pas toujours, mais mentionnez toute experience en contact client, meme hors restauration."], ["Quelles qualites mettre en avant ?", "Rapidite, sourire, resistance au stress, polyvalence et esprit d'equipe."], ["Lettre manuscrite ou email ?", "Email avec la lettre en piece jointe ou dans le corps du mail. La rapidite compte en restauration."]], temoignage: { nom: "Karim H.", poste: "Serveur en brasserie parisienne", texte: "Recrute en 48h apres avoir envoye la lettre generee par l'IA. Simple et efficace !" } },
  "comptable": { t: "Comptable", s: "Finance et gestion", d: "Vous postulez comme comptable ? Notre IA cree une lettre qui met en avant votre rigueur et vos competences techniques.", c: "Mentionnez vos diplomes, les logiciels maitrises et votre experience en cabinet ou entreprise.", ex: "Comptable en cabinet, en entreprise, aide-comptable, chef comptable", phrases: ["Ma maitrise de Sage et Cegid, associee a mon experience de [X] ans, garantit une gestion comptable fiable.", "Rigoureux et methodique, j'assure le suivi des ecritures comptables dans le respect des delais.", "Mon experience en cabinet m'a appris a gerer plusieurs dossiers clients simultanement."], faq: [["Quels logiciels mentionner ?", "Sage, Cegid, EBP, QuickBooks et Excel avance sont les plus demandes."], ["Le DCG est-il indispensable ?", "Le BTS CG suffit pour un poste d'aide-comptable. Le DCG ouvre plus de portes."], ["Comment se demarquer ?", "Mentionnez des resultats concrets : delais de cloture reduits, anomalies detectees, processus ameliores."]], temoignage: { nom: "Claire M.", poste: "Comptable en cabinet", texte: "Lettre professionnelle et technique, exactement ce que les cabinets attendent. Merci !" } },
  "assistant-administratif": { t: "Assistant(e) administratif(ve)", s: "Administration", d: "Vous postulez comme assistant administratif ? Notre IA redige une lettre qui valorise votre organisation.", c: "Les recruteurs cherchent des profils organises, autonomes et maitrisant le Pack Office.", ex: "Assistante de direction, assistant administratif, secretaire, assistante RH", phrases: ["Organisee et polyvalente, je gere efficacement les taches administratives au quotidien.", "Ma maitrise du Pack Office et des outils collaboratifs me permet d'etre operationnelle immediatement.", "Discrete et fiable, je suis le pilier administratif de toute equipe."], faq: [["Quelles competences sont les plus demandees ?", "Organisation, maitrise de Word/Excel, gestion d'agenda, accueil telephonique et redaction de courriers."], ["Faut-il des diplomes specifiques ?", "Un BTS SAM ou un titre professionnel est un plus, mais l'experience compte beaucoup."], ["Comment se demarquer ?", "Montrez votre polyvalence et votre capacite a gerer plusieurs taches simultanement."]], temoignage: { nom: "Sandrine T.", poste: "Assistante de direction", texte: "Une lettre claire et professionnelle. Mon nouveau patron m'a dit que c'est ce qui l'a convaincu !" } },
  "developpeur": { t: "Developpeur / Developpeuse", s: "Informatique et tech", d: "Vous postulez comme developpeur ? Notre IA genere une lettre technique adaptee au monde de la tech.", c: "Mentionnez vos langages, vos projets concrets et votre veille technologique.", ex: "Developpeur web, mobile, full-stack, front-end, Python, JavaScript", phrases: ["Passionne de code depuis [X] ans, je maitrise [langages] et j'ai contribue a [projet].", "Mon approche clean code et mon experience en methodologie agile sont des atouts pour votre equipe.", "Mon GitHub actif et mes contributions open-source temoignent de ma passion pour le developpement."], faq: [["Faut-il mentionner son GitHub ?", "Oui ! Un GitHub actif vaut plus que n'importe quel diplome dans la tech."], ["Lettre de motivation ou portfolio ?", "Les deux ! La lettre montre votre motivation, le portfolio montre vos competences."], ["Comment postuler en junior ?", "Mettez en avant vos projets personnels, vos formations et votre curiosite technologique."]], temoignage: { nom: "Maxime G.", poste: "Dev full-stack en start-up", texte: "La lettre a bien mis en valeur mon profil technique sans etre trop formelle. Parfait pour la tech !" } },
  "agent-dentretien": { t: "Agent d'entretien", s: "Nettoyage et hygiene", d: "Vous postulez comme agent d'entretien ? Notre IA cree une lettre qui met en avant votre serieux.", c: "Mettez en avant votre fiabilite, votre ponctualite et votre connaissance des techniques de nettoyage.", ex: "Agent d'entretien en entreprise, agent de proprete, femme de menage, agent hospitalier", phrases: ["Ponctuel et minutieux, j'assure un nettoyage impeccable dans le respect des normes d'hygiene.", "Mon experience de [X] ans m'a permis de maitriser les produits et techniques adaptes a chaque surface.", "Autonome et discret, je travaille efficacement sans perturber l'activite de l'entreprise."], faq: [["Faut-il une lettre pour ce type de poste ?", "Oui ! La plupart des candidats n'en envoient pas, c'est donc un excellent moyen de se demarquer."], ["Quelles qualites valoriser ?", "Ponctualite, serieux, discretion, autonomie et respect des consignes de securite."], ["Faut-il des diplomes ?", "Non, mais un CAP maintenance et hygiene des locaux est un plus."]], temoignage: { nom: "Marie-Louise K.", poste: "Agent d'entretien en entreprise", texte: "Grace a la lettre, j'ai ete choisie parmi 30 candidats. Cela fait toute la difference !" } },
  "chauffeur-livreur": { t: "Chauffeur-livreur", s: "Transport et logistique", d: "Vous postulez comme chauffeur-livreur ? Notre IA redige une lettre mettant en avant votre permis et votre ponctualite.", c: "Indiquez votre type de permis, votre connaissance de la zone et votre experience en livraison.", ex: "Chauffeur-livreur, livreur de colis, chauffeur poids lourd, chauffeur VTC", phrases: ["Titulaire du permis [type], je connais parfaitement la region [zone].", "Ponctuel et organise, je respecte les delais de livraison et les consignes de securite.", "Mon sens de l'orientation et ma maitrise du GPS me permettent d'optimiser mes tournees."], faq: [["Quel permis faut-il ?", "Le permis B suffit pour la livraison legere. Le permis C est necessaire pour les poids lourds."], ["Comment se demarquer ?", "Mentionnez votre ponctualite, votre connaissance de la zone et votre zero accident."], ["Faut-il mentionner son vehicule ?", "Si vous postulez comme livreur independant, oui."]], temoignage: { nom: "David R.", poste: "Livreur chez Chronopost", texte: "Simple et efficace, la lettre a mis en avant exactement ce que les transporteurs recherchent." } },
  "boulanger": { t: "Boulanger / Boulangere", s: "Artisanat et alimentation", d: "Vous postulez comme boulanger ? Notre IA genere une lettre qui met en avant votre savoir-faire artisanal.", c: "Parlez de votre formation, votre maitrise des techniques de panification et votre passion.", ex: "Boulanger artisanal, en grande surface, patissier-boulanger, apprenti boulanger", phrases: ["Passionne par l'art de la panification, je maitrise les techniques de fabrication du pain traditionnel.", "Matinal et rigoureux, je suis habitue aux horaires decales de la boulangerie.", "Mon CAP boulangerie et mes [X] ans d'experience garantissent un travail de qualite."], faq: [["Le CAP est-il obligatoire ?", "Il est fortement recommande et souvent exige pour les postes qualifies."], ["Comment montrer sa passion ?", "Parlez de vos specialites, de vos experiences et de ce qui vous plait dans ce metier."], ["Faut-il une lettre en boulangerie ?", "Oui ! Surtout dans les boulangeries artisanales qui cherchent des passionnes."]], temoignage: { nom: "Pierre B.", poste: "Boulanger artisanal", texte: "La lettre a su transmettre ma passion. Mon nouveau patron m'a dit qu'il avait senti mon amour du metier !" } },
  "caissier": { t: "Caissier / Caissiere", s: "Commerce et distribution", d: "Vous postulez comme caissier ou caissiere ? Notre IA cree une lettre mettant en avant votre rigueur et votre sourire.", c: "Montrez votre aisance avec la caisse, votre politesse et votre capacite a gerer les files.", ex: "Caissiere en supermarche, caissier en magasin, hotesse de caisse, employe libre-service", phrases: ["Souriante et rapide, je garantis un passage en caisse agreable pour chaque client.", "Ma rigueur dans la manipulation des fonds et la gestion de ma caisse est irreprochable.", "Polyvalente, je peux egalement assurer la mise en rayon et le conseil client."], faq: [["Faut-il de l'experience ?", "Non, beaucoup de postes de caissier sont ouverts aux debutants."], ["Quelles qualites mettre en avant ?", "Rapidite, precision, sourire, politesse et resistance a la station debout."], ["Peut-on postuler sans diplome ?", "Oui, c'est un poste accessible sans diplome specifique."]], temoignage: { nom: "Amina F.", poste: "Caissiere chez Carrefour", texte: "Premiere candidature, premier entretien, premier emploi. La lettre IA m'a porte chance !" } },
  "cuisinier": { t: "Cuisinier / Cuisiniere", s: "Restauration", d: "Vous postulez comme cuisinier ? Notre IA redige une lettre mettant en valeur votre creativite culinaire.", c: "Decrivez vos specialites, votre formation et votre capacite a travailler sous pression.", ex: "Cuisinier en restaurant, chef de partie, commis de cuisine, cuisinier en collectivite", phrases: ["Forme en cuisine traditionnelle francaise, je maitrise les techniques de base et les cuissons.", "Creatif et organise, je suis capable de gerer un service de [X] couverts.", "Mon experience en brigade m'a appris la rigueur, la rapidite et le respect de la hierarchie."], faq: [["Le CAP cuisine est-il necessaire ?", "Il est recommande, mais l'experience peut compenser l'absence de diplome."], ["Comment montrer sa creativite ?", "Mentionnez un plat signature ou une experience qui montre votre originalite."], ["Les restaurants recrutent-ils facilement ?", "Oui, c'est un secteur en forte tension. Les bons cuisiniers sont tres recherches."]], temoignage: { nom: "Antoine C.", poste: "Chef de partie", texte: "La lettre a montre ma passion et mes competences techniques. Recrute dans un restaurant etoile !" } },
  "educateur-specialise": { t: "Educateur specialise", s: "Social et educatif", d: "Vous postulez comme educateur specialise ? Notre IA genere une lettre adaptee au secteur social.", c: "Valorisez votre diplome DEES, vos stages et votre capacite a accompagner des publics en difficulte.", ex: "Educateur en foyer, de rue, PJJ, moniteur-educateur, educateur en IME", phrases: ["Mon diplome DEES et mes stages m'ont prepare a accompagner des publics vulnerables.", "Empathique et patient, je sais etablir une relation educative basee sur la confiance.", "Mon experience aupres de [public] m'a appris a adapter mes interventions a chaque situation."], faq: [["Le DEES est-il obligatoire ?", "Oui, le Diplome d'Etat d'Educateur Specialise est requis pour exercer."], ["Comment parler de sa motivation ?", "Expliquez pourquoi le travail social vous anime et racontez une experience marquante."], ["Quel type de lettre privilegier ?", "Une lettre sincere et engagee, qui montre votre connaissance du public accompagne."]], temoignage: { nom: "Youssuf O.", poste: "Educateur en foyer", texte: "La lettre a parfaitement traduit mon engagement social. Le directeur l'a trouvee tres pertinente." } },
  "electricien": { t: "Electricien", s: "BTP et artisanat", d: "Vous postulez comme electricien ? Notre IA cree une lettre technique mettant en avant vos habilitations.", c: "Mentionnez vos habilitations electriques, votre CAP/BEP et votre experience terrain.", ex: "Electricien du batiment, industriel, auto-entrepreneur, technicien electricien", phrases: ["Titulaire des habilitations BR, B1V et B2V, j'interviens en toute securite.", "Mon CAP electricien et mes [X] ans d'experience me rendent autonome sur tous types de chantiers.", "Je maitrise les installations domestiques, tertiaires et industrielles."], faq: [["Les habilitations sont-elles obligatoires ?", "Oui, elles sont legalement requises pour travailler sur des installations electriques."], ["Faut-il un diplome ?", "Un CAP electricien est le minimum requis. Le BP permet d'evoluer."], ["Comment se demarquer ?", "Mentionnez vos specialites (domotique, panneaux solaires, fibre) et vos formations complementaires."]], temoignage: { nom: "Julien M.", poste: "Electricien du batiment", texte: "Ma lettre a ete remarquee pour son professionnalisme. Embauche directe en CDI !" } },
  "hotesse-daccueil": { t: "Hotesse d'accueil", s: "Accueil et relation client", d: "Vous postulez comme hotesse d'accueil ? Notre IA redige une lettre mettant en avant votre presentation et votre professionnalisme.", c: "Les recruteurs cherchent une excellente presentation, la maitrise de langues et un sens du service.", ex: "Hotesse en entreprise, evenementiel, standardiste, receptionniste", phrases: ["Ma presentation soignee et mon sourire naturel sont mes meilleurs atouts.", "Bilingue francais-anglais, je suis a l'aise avec une clientele internationale.", "Mon experience en accueil m'a appris a gerer les situations delicates avec diplomatie."], faq: [["Faut-il parler anglais ?", "C'est un gros plus, surtout dans les grandes entreprises et l'evenementiel."], ["Quelle tenue pour l'entretien ?", "Tenue professionnelle et soignee, coherente avec le poste d'accueil."], ["L'experience est-elle indispensable ?", "Non, une bonne presentation et un excellent relationnel suffisent souvent."]], temoignage: { nom: "Charlotte L.", poste: "Hotesse d'accueil chez LVMH", texte: "La lettre etait elegante et professionnelle, a l'image du poste. Parfait !" } },
  "ingenieur": { t: "Ingenieur", s: "Ingenierie et technique", d: "Vous postulez comme ingenieur ? Notre IA genere une lettre professionnelle adaptee au monde de l'ingenierie.", c: "Mettez en avant votre ecole, vos projets techniques et votre capacite a resoudre des problemes complexes.", ex: "Ingenieur informatique, mecanique, civil, agronome, commercial", phrases: ["Diplome de [ecole], je possede une solide expertise en [domaine].", "Mon approche analytique et ma rigueur scientifique sont des atouts pour vos projets.", "Mon experience sur le projet [nom] m'a permis de developper des competences en [domaine]."], faq: [["Faut-il mentionner son ecole ?", "Oui, l'ecole d'ingenieur est un element important pour les recruteurs en France."], ["Comment valoriser ses projets ?", "Decrivez un projet concret, votre role et les resultats obtenus."], ["Lettre technique ou generale ?", "Un mix des deux : montrez vos competences techniques ET vos qualites humaines."]], temoignage: { nom: "Alexandre D.", poste: "Ingenieur chez Airbus", texte: "La lettre a su equilibrer technique et personnalite. Exactement ce que les grands groupes recherchent." } },
  "manutentionnaire": { t: "Manutentionnaire", s: "Logistique et entreposage", d: "Vous postulez comme manutentionnaire ? Notre IA cree une lettre mettant en avant votre endurance et votre serieux.", c: "Indiquez si vous avez le CACES, votre experience en entrepot et votre rigueur.", ex: "Manutentionnaire en entrepot, preparateur de commandes, cariste, magasinier", phrases: ["Titulaire du CACES [categorie], je maitrise la conduite de chariots elevateurs.", "Endurant et rigoureux, je respecte les consignes de securite en toute circonstance.", "Mon experience en entrepot logistique m'a rendu rapide et efficace dans la manutention."], faq: [["Le CACES est-il obligatoire ?", "Pas toujours, mais il est un gros plus et souvent exige pour la conduite d'engins."], ["Faut-il une lettre pour ce type de poste ?", "Oui ! Peu de candidats en envoient, c'est un avantage concurrentiel."], ["Quelles qualites valoriser ?", "Endurance physique, ponctualite, rigueur et respect des consignes de securite."]], temoignage: { nom: "Ibrahima S.", poste: "Manutentionnaire chez Amazon", texte: "La lettre m'a demarque des autres candidats. J'ai ete rappele le jour meme !" } },
  "mecanicien": { t: "Mecanicien / Mecanicienne", s: "Automobile et maintenance", d: "Vous postulez comme mecanicien ? Notre IA redige une lettre technique mettant en avant vos competences en diagnostic.", c: "Decrivez vos certifications, les marques maitrisees et vos outils de diagnostic.", ex: "Mecanicien automobile, poids lourd, moto, technicien de maintenance", phrases: ["Ma maitrise du diagnostic electronique me permet d'identifier rapidement les pannes.", "Forme sur les vehicules [marques], je maitrise l'ensemble des operations de maintenance.", "Passionne d'automobile depuis toujours, je traite chaque vehicule avec le plus grand soin."], faq: [["Quelles certifications mentionner ?", "CAP mecanicien, BAC pro maintenance vehicules, certifications constructeurs."], ["Comment se demarquer ?", "Mentionnez vos specialites (hybride, electrique, climatisation) et vos outils maitrises."], ["Le secteur recrute-t-il ?", "Oui, les garages peinent a trouver des mecaniciens qualifies. C'est un metier en tension."]], temoignage: { nom: "Kevin P.", poste: "Mecanicien chez Renault", texte: "La lettre technique et passionnee a convaincu le chef d'atelier. En poste depuis 6 mois !" } },
  "pharmacien": { t: "Pharmacien / Pharmacienne", s: "Sante et pharmacie", d: "Vous postulez comme pharmacien ? Notre IA genere une lettre adaptee au secteur pharmaceutique.", c: "Valorisez votre diplome, vos stages officinaux et votre sens du conseil patient.", ex: "Pharmacien d'officine, hospitalier, en industrie, preparateur en pharmacie", phrases: ["Docteur en pharmacie, je possede une expertise approfondie en conseil pharmaceutique.", "Ma rigueur dans la delivrance des medicaments garantit la securite des patients.", "Mon sens de l'ecoute me permet d'adapter mes conseils a chaque patient."], faq: [["Le doctorat est-il indispensable ?", "Oui pour exercer comme pharmacien. Les preparateurs ont un BP specifique."], ["Comment se demarquer ?", "Mentionnez vos specialites (phytotherapie, dermocosmetique, maintien a domicile)."], ["Les officines recrutent-elles ?", "Oui, beaucoup d'officines cherchent des pharmaciens adjoints et des preparateurs."]], temoignage: { nom: "Sophie R.", poste: "Pharmacienne adjointe", texte: "Lettre professionnelle et adaptee au monde officinal. Recrutee dans ma pharmacie preferee !" } },
  "plombier": { t: "Plombier", s: "BTP et artisanat", d: "Vous postulez comme plombier ? Notre IA cree une lettre mettant en avant votre savoir-faire et votre experience.", c: "Mentionnez vos qualifications, votre experience en depannage et installation, et votre autonomie.", ex: "Plombier chauffagiste, sanitaire, depanneur, technicien plombier", phrases: ["Mon CAP installateur sanitaire et mes [X] ans d'experience font de moi un plombier qualifie.", "Autonome et reactif, j'interviens aussi bien en depannage qu'en installation neuve.", "Ma maitrise des normes DTU et des reglementations en vigueur garantit un travail conforme."], faq: [["Quelles qualifications faut-il ?", "Un CAP installateur sanitaire ou thermique est le minimum. Le BP permet de s'installer."], ["Faut-il une lettre en plomberie ?", "Oui, surtout si vous postulez dans une entreprise structuree ou en collectivite."], ["Comment se demarquer ?", "Mentionnez vos specialites (pompe a chaleur, plancher chauffant, energies renouvelables)."]], temoignage: { nom: "Christophe N.", poste: "Plombier chauffagiste", texte: "La lettre a montre mon professionnalisme. J'ai ete embauche en CDI chez un grand groupe du BTP." } },
  "professeur": { t: "Professeur / Enseignant", s: "Education et formation", d: "Vous postulez comme professeur ? Notre IA redige une lettre mettant en valeur votre pedagogie.", c: "Parlez de votre approche pedagogique, vos diplomes et votre capacite a adapter votre enseignement.", ex: "Professeur des ecoles, de maths, de francais, enseignant contractuel, formateur", phrases: ["Ma passion pour la transmission des savoirs guide mon enseignement depuis [X] ans.", "J'adapte mes methodes pedagogiques aux besoins specifiques de chaque eleve.", "Mon approche innovante et bienveillante favorise l'engagement et la reussite des apprenants."], faq: [["Le CAPES est-il obligatoire ?", "Pour etre titulaire, oui. Les contractuels peuvent enseigner avec un master."], ["Comment se demarquer ?", "Parlez de votre approche pedagogique concrete, pas seulement de vos diplomes."], ["Les lettres comptent-elles dans l'Education nationale ?", "Oui, surtout pour les postes de contractuels et dans l'enseignement prive."]], temoignage: { nom: "Camille J.", poste: "Professeure de francais", texte: "La lettre a montre ma passion pour l'enseignement. Le principal du college a ete convaincu !" } },
  "secretaire": { t: "Secretaire", s: "Administration et bureau", d: "Vous postulez comme secretaire ? Notre IA genere une lettre mettant en avant votre organisation et votre discretion.", c: "Mettez en avant votre maitrise de Word, Excel, votre rapidite de frappe et votre sens de la confidentialite.", ex: "Secretaire medicale, juridique, de direction, comptable, administrative", phrases: ["Ma maitrise des outils bureautiques et ma rapidite de frappe sont des atouts quotidiens.", "Discrete et organisee, je gere les agendas et la correspondance avec precision.", "Mon experience de secretariat m'a appris a anticiper les besoins et a etre proactive."], faq: [["Quels logiciels maitriser ?", "Word, Excel, PowerPoint, Outlook et idealement un logiciel metier (Doctolib, etc.)."], ["Faut-il un diplome specifique ?", "Un BTS SAM ou un titre professionnel est recommande."], ["Comment se demarquer ?", "Mentionnez votre rapidite de frappe, votre discretion et votre capacite d'adaptation."]], temoignage: { nom: "Valerie G.", poste: "Secretaire medicale", texte: "La lettre etait parfaitement adaptee au medical. J'ai ete embauchee dans le cabinet de mes reves !" } },
  "technicien-informatique": { t: "Technicien informatique", s: "Informatique et support", d: "Vous postulez comme technicien informatique ? Notre IA cree une lettre mettant en avant vos competences en support.", c: "Decrivez vos certifications, votre experience en helpdesk et votre maitrise des systemes.", ex: "Technicien helpdesk, reseau, systemes, administrateur, support IT", phrases: ["Certifie [certification], je resous efficacement les incidents de niveau 1 a 3.", "Ma patience et ma pedagogie me permettent d'accompagner les utilisateurs de tous niveaux.", "Je maitrise les environnements Windows Server, Linux et les reseaux TCP/IP."], faq: [["Quelles certifications mentionner ?", "CompTIA A+, ITIL, Microsoft, Cisco CCNA sont les plus valorisees."], ["L'experience prime-t-elle sur les diplomes ?", "En informatique, oui. L'experience pratique et les certifications comptent enormement."], ["Comment montrer sa valeur ?", "Mentionnez le nombre de tickets resolus par jour ou votre taux de satisfaction utilisateur."]], temoignage: { nom: "Romain F.", poste: "Technicien helpdesk", texte: "La lettre a bien mis en valeur mes certifications et mon experience terrain. Recrute en ESN !" } },
  "agent-immobilier": { t: "Agent immobilier", s: "Immobilier", d: "Vous postulez comme agent immobilier ? Notre IA redige une lettre commerciale mettant en avant votre talent de negociateur.", c: "Montrez votre connaissance du marche local, votre reseau et vos resultats de vente.", ex: "Agent en agence, negociateur immobilier, conseiller, mandataire independant", phrases: ["Ma connaissance approfondie du marche immobilier local est un atout majeur.", "En [X] ans, j'ai realise [X] transactions pour un volume total de [X] millions d'euros.", "Mon reseau de contacts et ma maitrise des techniques de negociation garantissent des resultats."], faq: [["La carte professionnelle est-elle obligatoire ?", "Elle est necessaire pour exercer de maniere independante. Les negociateurs travaillent sous la carte de l'agence."], ["Comment se demarquer ?", "Chiffrez vos resultats : nombre de ventes, volume, delai moyen de vente."], ["Le marche immobilier recrute-t-il ?", "Oui, notamment les profils commerciaux motives avec une bonne connaissance locale."]], temoignage: { nom: "Stephanie W.", poste: "Negociatrice immobiliere", texte: "La lettre a mis en avant mes chiffres de vente. L'agence m'a rappele dans l'heure !" } },
  "animateur": { t: "Animateur / Animatrice", s: "Animation et loisirs", d: "Vous postulez comme animateur ? Notre IA genere une lettre dynamique mettant en avant votre energie et votre creativite.", c: "Parlez de votre BAFA, vos experiences en centre de loisirs et votre capacite a encadrer des groupes.", ex: "Animateur centre de loisirs, periscolaire, colonie, sportif, EHPAD", phrases: ["Titulaire du BAFA, j'ai encadre des groupes de [X] enfants lors de [experience].", "Creatif et dynamique, je propose des activites ludiques adaptees a chaque tranche d'age.", "Ma bonne humeur et mon energie sont contagieuses, les enfants comme les parents l'apprecient."], faq: [["Le BAFA est-il obligatoire ?", "Il est tres recommande et souvent exige pour les postes en centres de loisirs."], ["Comment se demarquer ?", "Parlez de vos specialites : sport, arts plastiques, musique, theatre, nature."], ["Peut-on postuler sans experience ?", "Oui, avec le BAFA et de la motivation, beaucoup de structures acceptent les debutants."]], temoignage: { nom: "Hugo T.", poste: "Animateur en colonie", texte: "Ma lettre etait pleine d'energie, comme moi ! Le directeur du centre m'a pris tout de suite." } },
  "auxiliaire-de-vie": { t: "Auxiliaire de vie", s: "Aide a la personne", d: "Vous postulez comme auxiliaire de vie ? Notre IA redige une lettre humaine mettant en avant votre devouement.", c: "Mettez en avant votre diplome, votre experience avec les personnes agees ou handicapees et votre patience.", ex: "Auxiliaire de vie a domicile, aide a domicile, accompagnant educatif et social", phrases: ["Mon DEAVS et mes [X] ans d'experience m'ont appris a accompagner avec respect et dignite.", "Patiente et attentionnee, je m'adapte aux besoins specifiques de chaque personne accompagnee.", "Mon objectif est de maintenir l'autonomie et le bien-etre des personnes que j'accompagne."], faq: [["Faut-il un diplome ?", "Le DEAVS ou le titre ADVF est recommande. L'experience peut parfois suffire."], ["Comment montrer son empathie ?", "Racontez une experience concrete ou vous avez fait la difference dans la vie d'une personne."], ["Le secteur recrute-t-il ?", "Enormement ! Le vieillissement de la population cree une forte demande."]], temoignage: { nom: "Patricia M.", poste: "Auxiliaire de vie a domicile", texte: "La lettre a su montrer mon coeur et mon professionnalisme. Mes beneficiaires sont ravis de m'avoir !" } },
  "coiffeur": { t: "Coiffeur / Coiffeuse", s: "Beaute et esthetique", d: "Vous postulez comme coiffeur ou coiffeuse ? Notre IA genere une lettre creative mettant en avant votre talent.", c: "Parlez de votre CAP/BP coiffure, vos specialites et votre sens du conseil client.", ex: "Coiffeuse en salon, coiffeur a domicile, barbier, coloriste, manager de salon", phrases: ["Passionnee par la coiffure, je maitrise les techniques de coupe, coloration et coiffage.", "Mon sens artistique et mon ecoute me permettent de sublimer chaque client.", "Formee aux dernieres tendances, je propose des coupes modernes et adaptees a chaque visage."], faq: [["Le CAP coiffure est-il obligatoire ?", "Oui pour exercer comme salarie. Le BP est necessaire pour ouvrir son salon."], ["Comment se demarquer ?", "Montrez vos realisations (photos, Instagram) et vos specialites."], ["Le secteur recrute-t-il ?", "Oui, les bons coiffeurs sont toujours recherches, surtout en coloriste et barbier."]], temoignage: { nom: "Melissa A.", poste: "Coiffeuse coloriste", texte: "La lettre a montre ma passion et ma technique. J'ai integre le salon de mes reves !" } },
  "gestionnaire-de-paie": { t: "Gestionnaire de paie", s: "Ressources humaines", d: "Vous postulez comme gestionnaire de paie ? Notre IA redige une lettre technique mettant en avant votre rigueur.", c: "Mentionnez votre maitrise des logiciels de paie, votre connaissance du droit social et votre precision.", ex: "Gestionnaire de paie en cabinet, en entreprise, technicien paie, assistant paie", phrases: ["Ma maitrise de Sage, Cegid et Silae me permet de gerer [X] bulletins de paie mensuels.", "Rigoureux et a jour sur les evolutions legales, je garantis des paies conformes et ponctuelles.", "Mon experience en cabinet m'a confronte a des conventions collectives variees."], faq: [["Quels logiciels maitriser ?", "Sage Paie, Cegid, Silae, ADP et DSN sont les plus demandes."], ["Faut-il connaitre le droit social ?", "C'est essentiel. Les recruteurs attendent une bonne connaissance de la legislation."], ["Comment evoluer ?", "Vers responsable paie, responsable RH ou consultant en paie."]], temoignage: { nom: "Aurelie P.", poste: "Gestionnaire de paie en cabinet", texte: "La lettre a montre ma rigueur technique. Recrutee dans un grand cabinet comptable !" } },
  "graphiste": { t: "Graphiste / Designer", s: "Creation et design", d: "Vous postulez comme graphiste ? Notre IA genere une lettre creative mettant en avant votre univers visuel.", c: "Mentionnez votre portfolio, vos outils et vos projets les plus marquants.", ex: "Graphiste freelance, directeur artistique, webdesigner, UX designer, infographiste", phrases: ["Mon univers visuel allie creativite et efficacite pour servir votre communication.", "Je maitrise la suite Adobe, Figma et les outils de prototypage UX.", "Mes realisations pour [client/projet] ont genere [resultat mesurable]."], faq: [["Le portfolio est-il indispensable ?", "Absolument ! Un graphiste sans portfolio n'a aucune chance. C'est plus important que la lettre."], ["Faut-il un diplome ?", "Un BTS design graphique ou une ecole d'art est un plus, mais le portfolio prime."], ["Lettre creative ou classique ?", "Restez professionnel mais montrez votre personnalite. La lettre IA + votre portfolio = combo gagnant."]], temoignage: { nom: "Quentin B.", poste: "Graphiste en agence", texte: "La lettre a complete mon portfolio avec les bons mots. Le DA a ete convaincu !" } },
  "preparateur-de-commandes": { t: "Preparateur de commandes", s: "Logistique et entreposage", d: "Vous postulez comme preparateur de commandes ? Notre IA cree une lettre mettant en avant votre rapidite et votre precision.", c: "Mentionnez votre CACES, votre experience en entrepot et votre rigueur dans la preparation.", ex: "Preparateur en entrepot, picker, agent logistique, preparateur drive, preparateur e-commerce", phrases: ["Rapide et precis, je prepare en moyenne [X] commandes par heure sans erreur.", "Titulaire du CACES [categorie], je suis autonome dans l'entrepot.", "Mon sens de l'organisation me permet de respecter les delais meme en periode de forte activite."], faq: [["Le CACES est-il necessaire ?", "Pas toujours, mais c'est un avantage majeur. Beaucoup d'employeurs le financent."], ["Faut-il de l'experience ?", "Non, beaucoup de postes sont ouverts aux debutants, surtout en interim."], ["Comment se demarquer ?", "Mentionnez votre rapidite, votre taux d'erreur faible et votre disponibilite."]], temoignage: { nom: "Moussa D.", poste: "Preparateur chez Amazon", texte: "Simple et efficace, la lettre m'a permis d'etre selectionne parmi 50 candidats." } },
  "receptionniste": { t: "Receptionniste", s: "Hotellerie et accueil", d: "Vous postulez comme receptionniste ? Notre IA redige une lettre mettant en avant votre sens de l'accueil et vos langues.", c: "Les hotels cherchent des profils bilingues, souriants et maitrisant les logiciels de reservation.", ex: "Receptionniste d'hotel, night auditor, concierge, agent de reservation", phrases: ["Bilingue francais-anglais, j'accueille les clients internationaux avec aisance et professionnalisme.", "Ma maitrise de Opera et Mews me permet de gerer les reservations efficacement.", "Mon sourire et ma disponibilite garantissent un accueil chaleureux a chaque client."], faq: [["Combien de langues faut-il parler ?", "Deux minimum (francais + anglais). Une troisieme langue est un gros avantage."], ["Faut-il un diplome hotelier ?", "Un BTS hotellerie-restauration est un plus, mais l'experience en accueil peut suffire."], ["Les horaires sont-ils difficiles ?", "Oui, les receptionnistes travaillent souvent en horaires decales, week-ends et jours feries."]], temoignage: { nom: "Olga S.", poste: "Receptionniste au Marriott", texte: "La lettre trilingue generee par l'IA a impressionne le directeur de l'hotel !" } },
  "responsable-marketing": { t: "Responsable marketing", s: "Marketing et communication", d: "Vous postulez comme responsable marketing ? Notre IA genere une lettre strategique mettant en avant vos resultats.", c: "Chiffrez vos resultats (ROI, taux de conversion, croissance) et mentionnez vos competences digitales.", ex: "Responsable marketing digital, chef de produit, brand manager, growth manager", phrases: ["Ma strategie digitale a genere une croissance de [X]% du CA en [duree].", "Expert en acquisition et retention, je maitrise Google Ads, Meta Ads et le marketing automation.", "Mon approche data-driven me permet d'optimiser chaque euro investi en marketing."], faq: [["Faut-il chiffrer ses resultats ?", "Absolument. Un responsable marketing sans KPIs, c'est comme un commercial sans chiffres."], ["Quels outils mentionner ?", "Google Analytics, HubSpot, Mailchimp, Meta Business Suite, SEMrush sont les plus demandes."], ["Comment se demarquer ?", "Racontez une campagne concrete avec le probleme, la solution et les resultats."]], temoignage: { nom: "Laura V.", poste: "Responsable marketing digital", texte: "La lettre IA a su mettre en valeur mes KPIs de maniere percutante. Recrutee en scale-up !" } },
  "technicien-de-maintenance": { t: "Technicien de maintenance", s: "Industrie et maintenance", d: "Vous postulez comme technicien de maintenance ? Notre IA redige une lettre technique mettant en avant vos competences.", c: "Decrivez vos habilitations, vos competences en mecanique, electrique et automatisme.", ex: "Technicien de maintenance industrielle, SAV, CVC, maintenance batiment", phrases: ["Polyvalent en mecanique, electrique et pneumatique, j'interviens sur tout type d'equipement.", "Mon experience en maintenance preventive a reduit les pannes de [X]% dans mon service.", "Reactif et methodique, je diagnostique et repare les pannes dans les meilleurs delais."], faq: [["Quelles competences sont les plus recherchees ?", "Electricite, mecanique, automatisme, pneumatique et de plus en plus la maintenance de robots."], ["Faut-il des habilitations ?", "Les habilitations electriques sont quasi obligatoires. Le CACES est un plus."], ["Le secteur recrute-t-il ?", "Enormement ! C'est l'un des metiers les plus en tension en France."]], temoignage: { nom: "Nicolas H.", poste: "Technicien de maintenance industrielle", texte: "La lettre technique et structuree a convaincu le responsable de production. CDI signe !" } },
  "parcoursup": { t: "Parcoursup", s: "Orientation post-bac", d: "Vous redigez votre lettre de motivation Parcoursup ? Notre IA vous aide a formuler un projet de formation convaincant.", c: "Expliquez votre projet professionnel, pourquoi cette formation et vos resultats scolaires pertinents.", ex: "Licence de droit, BTS commerce, classe preparatoire, ecole d'ingenieur, IUT, PASS medecine", phrases: ["Mon projet professionnel en [domaine] s'inscrit naturellement dans votre formation.", "Mes resultats en [matiere] et mon investissement dans [activite] temoignent de ma motivation.", "Votre formation represente pour moi l'etape essentielle vers mon objectif de devenir [metier]."], faq: [["Combien de caracteres pour Parcoursup ?", "1500 caracteres maximum. Chaque mot compte, soyez precis et concis."], ["Faut-il personnaliser pour chaque voeu ?", "Oui ! Les formations repèrent facilement les lettres generiques. Personnalisez chacune."], ["Que mettre si on n'a pas de projet precis ?", "Expliquez ce qui vous attire dans le domaine et les debouches qui vous interessent."]], temoignage: { nom: "Ines C.", poste: "Admise en licence de droit", texte: "Ma lettre Parcoursup etait bien structuree et convaincante. Acceptee dans mon premier voeu !" } },
}

const SITE = "https://lettredemotivation-ia.fr"

export async function getStaticPaths() {
  return { paths: Object.keys(M).map(s => ({ params: { metier: `lettre-de-motivation-${s}` } })), fallback: false }
}

export async function getStaticProps({ params }) {
  const slug = params.metier.replace("lettre-de-motivation-", "")
  const data = M[slug] || null
  if (!data) return { notFound: true }
  return { props: { slug, ...data } }
}

export default function PageMetier({ slug, t: titre, s: secteur, d: desc, c: conseils, ex: exemples, phrases, faq, temoignage }) {
  const [openFaq, setOpenFaq] = useState(null)
  const font = "'Instrument Serif', Georgia, serif"
  const sans = "'DM Sans', system-ui, sans-serif"
  const g = "#059669"
  const b = "#2563eb"

  const Section = ({ bg, children, pad }) => <div style={{ background: bg || "transparent", padding: pad || "64px 0" }}><div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px" }}>{children}</div></div>
  const SectionTitle = ({ children, white }) => <div style={{ fontSize: 20, fontWeight: 700, textTransform: "uppercase", letterSpacing: 2.5, marginBottom: 24, color: white ? "#fff" : "#1e293b", fontFamily: sans }}>{children}</div>
  const CTA = ({ white }) => <a href="/" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "14px 32px", borderRadius: 10, background: white ? "#fff" : `linear-gradient(135deg, ${g}, ${b})`, color: white ? g : "#fff", fontSize: 15, fontWeight: 600, textDecoration: "none", boxShadow: `0 8px 32px ${white ? "rgba(0,0,0,0.15)" : "rgba(5,150,105,0.2)"}` }}>Generer ma lettre gratuitement</a>

  return (
    <>
      <Head>
        <title>{`Lettre de motivation ${titre} - Generateur IA gratuit`}</title>
        <meta name="description" content={`Generez votre lettre de motivation ${titre.toLowerCase()} en 30 secondes avec l'IA. Personnalisee, aux normes francaises, gratuite.`} />
        <meta property="og:title" content={`Lettre de motivation ${titre} - IA`} />
        <meta property="og:description" content={desc} />
        <meta property="og:url" content={`${SITE}/lettre-de-motivation-${slug}`} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet" />
      </Head>

      <div style={{ fontFamily: sans, color: "#1e293b", background: "#fff", minHeight: "100vh" }}>

        {/* Nav */}
        <Section pad="24px 0 0">
          <a href="/" style={{ display: "inline-flex", alignItems: "center", border: "1.5px solid #1e293b", borderRadius: 8, padding: "8px 16px", gap: 8, textDecoration: "none" }}>
            <span style={{ fontSize: 14, fontWeight: 600, color: "#1e293b", textTransform: "uppercase", letterSpacing: 2 }}>Lettre de motivation</span>
            <span style={{ width: 1.5, height: 18, background: "#94a3b8", opacity: 0.3 }} />
            <span style={{ fontSize: 16, fontWeight: 700, letterSpacing: 3, background: `linear-gradient(135deg, ${g}, ${b})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>IA</span>
          </a>
        </Section>

        {/* Hero */}
        <Section pad="48px 0 56px">
          <div style={{ fontSize: 12, fontWeight: 600, color: g, textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>{secteur}</div>
          <h1 style={{ fontFamily: font, fontSize: 42, fontWeight: 400, lineHeight: 1.12, letterSpacing: -1, marginBottom: 20 }}>
            Lettre de motivation<br /><span style={{ fontStyle: "italic", background: `linear-gradient(135deg, ${g}, ${b})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{titre}</span>
          </h1>
          <p style={{ fontSize: 17, lineHeight: 1.7, color: "#64748b", marginBottom: 32, maxWidth: 560 }}>{desc}</p>
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
            <CTA />
            <a href="/" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "14px 32px", borderRadius: 10, background: "#f5f7fa", color: "#1e293b", fontSize: 15, fontWeight: 500, textDecoration: "none", border: "1px solid rgba(0,0,0,0.08)" }}>Voir les prix</a>
          </div>
        </Section>

        {/* Stats */}
        <div style={{ background: "linear-gradient(135deg, #0f172a, #1e293b)", padding: "48px 0" }}>
          <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px", display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 16, textAlign: "center" }}>
            {[{ n: "30s", l: "de generation" }, { n: "98%", l: "de satisfaction" }, { n: "0 EUR", l: "pour 2 lettres" }].map((f, i) => (
              <div key={i} style={{ padding: "16px 8px" }}>
                <div style={{ fontSize: 28, fontWeight: 700, color: "#fff" }}>{f.n}</div>
                <div style={{ fontSize: 12, color: "rgba(255,255,255,0.55)", marginTop: 4 }}>{f.l}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Exemples de phrases */}
        <Section bg="#fff">
          <SectionTitle>Exemples de phrases pour votre lettre {titre.toLowerCase()}</SectionTitle>
          <p style={{ fontSize: 14, color: "#64748b", marginBottom: 20, lineHeight: 1.6 }}>Notre IA genere des phrases personnalisees comme celles-ci, adaptees a votre profil :</p>
          {phrases.map((p, i) => (
            <div key={i} style={{ display: "flex", gap: 14, marginBottom: 16, padding: "16px 20px", background: "#f8fafc", borderRadius: 12, borderLeft: `3px solid ${i === 0 ? g : i === 1 ? b : "#7c3aed"}` }}>
              <div style={{ fontSize: 20, color: "#94a3b8", fontFamily: font, fontStyle: "italic" }}>"</div>
              <p style={{ fontSize: 14, lineHeight: 1.7, color: "#475569", margin: 0, fontStyle: "italic" }}>{p}</p>
            </div>
          ))}
          <div style={{ marginTop: 24 }}><CTA /></div>
        </Section>

        {/* Conseils */}
        <Section bg="#f5f7fa">
          <SectionTitle>Nos conseils pour votre lettre</SectionTitle>
          <p style={{ fontSize: 16, lineHeight: 1.8, color: "#475569", marginBottom: 24 }}>{conseils}</p>
          <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.06)", borderRadius: 12, padding: "20px 24px" }}>
            <div style={{ fontSize: 13, fontWeight: 600, color: g, textTransform: "uppercase", letterSpacing: 1, marginBottom: 8 }}>Postes concernes</div>
            <p style={{ fontSize: 14, lineHeight: 1.7, color: "#64748b", margin: 0 }}>{exemples}</p>
          </div>
        </Section>

        {/* Temoignage */}
        <Section bg="#fff">
          <div style={{ background: `linear-gradient(135deg, rgba(5,150,105,0.04), rgba(37,99,235,0.04))`, border: `1px solid rgba(5,150,105,0.12)`, borderRadius: 16, padding: "32px 28px", textAlign: "center" }}>
            <div style={{ fontSize: 32, color: g, fontFamily: font, marginBottom: 8 }}>"</div>
            <p style={{ fontSize: 16, lineHeight: 1.8, color: "#475569", fontStyle: "italic", marginBottom: 16, maxWidth: 500, margin: "0 auto 16px" }}>{temoignage.texte}</p>
            <div style={{ fontSize: 14, fontWeight: 600, color: "#1e293b" }}>{temoignage.nom}</div>
            <div style={{ fontSize: 12, color: "#64748b" }}>{temoignage.poste}</div>
          </div>
        </Section>

        {/* FAQ */}
        <Section bg="#f5f7fa">
          <SectionTitle>Questions frequentes - Lettre de motivation {titre.toLowerCase()}</SectionTitle>
          {faq.map(([q, a], i) => (
            <div key={i} onClick={() => setOpenFaq(openFaq === i ? null : i)} style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.06)", borderRadius: 12, marginBottom: 10, cursor: "pointer", overflow: "hidden" }}>
              <div style={{ padding: "16px 20px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ fontSize: 14, fontWeight: 500, color: "#1e293b" }}>{q}</span>
                <span style={{ fontSize: 18, color: "#94a3b8", transform: openFaq === i ? "rotate(45deg)" : "none", transition: "transform 0.2s" }}>+</span>
              </div>
              {openFaq === i && <div style={{ padding: "0 20px 16px", fontSize: 14, lineHeight: 1.7, color: "#64748b" }}>{a}</div>}
            </div>
          ))}
        </Section>

        {/* Pricing teaser */}
        <Section bg="#fff">
          <div style={{ textAlign: "center" }}>
            <SectionTitle>Des lettres a partir de 1 EUR</SectionTitle>
            <p style={{ fontSize: 15, color: "#64748b", lineHeight: 1.7, maxWidth: 440, margin: "0 auto 24px" }}>2 lettres gratuites pour tester. Ensuite, des packs a partir de 1,99 EUR. Moins cher qu'un cafe, plus efficace qu'une heure de redaction.</p>
            <div style={{ display: "inline-grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 24 }}>
              {[{ n: "1 lettre", p: "1,99 EUR" }, { n: "5 lettres", p: "4,99 EUR" }, { n: "15 lettres", p: "9,99 EUR" }, { n: "50 lettres", p: "19,99 EUR" }].map((pack, i) => (
                <div key={i} style={{ padding: "14px 24px", borderRadius: 10, background: i === 1 ? "rgba(5,150,105,0.06)" : "#f8fafc", border: i === 1 ? `1.5px solid rgba(5,150,105,0.2)` : "1px solid rgba(0,0,0,0.06)", textAlign: "center" }}>
                  <div style={{ fontSize: 14, fontWeight: 600, color: "#1e293b" }}>{pack.n}</div>
                  <div style={{ fontSize: 18, fontWeight: 700, color: g }}>{pack.p}</div>
                </div>
              ))}
            </div>
            <div><CTA /></div>
          </div>
        </Section>

        {/* CTA final */}
        <div style={{ background: `linear-gradient(135deg, ${g}, #047857, #0f766e)`, padding: "56px 0" }}>
          <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px", textAlign: "center" }}>
            <SectionTitle white>Pret a creer votre lettre {titre.toLowerCase()} ?</SectionTitle>
            <p style={{ fontSize: 15, color: "rgba(255,255,255,0.75)", lineHeight: 1.7, maxWidth: 420, margin: "0 auto 28px" }}>L'IA redige votre lettre de motivation {titre.toLowerCase()} en 30 secondes. 2 essais gratuits, sans carte bancaire.</p>
            <CTA white />
          </div>
        </div>

        {/* Footer */}
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "32px 24px", textAlign: "center" }}>
          <p style={{ fontSize: 12, color: "#94a3b8" }}>lettredemotivation-ia.fr - Generateur de lettres de motivation par intelligence artificielle</p>
        </div>
      </div>
    </>
  )
}
