import Head from 'next/head'

const METIERS = {
  "vendeuse": { titre: "Vendeuse / Vendeur", secteur: "Commerce et vente", desc: "Vous postulez comme vendeuse ou vendeur ? Notre IA genere une lettre de motivation personnalisee qui met en valeur votre sens du contact client, votre dynamisme et votre experience en vente.", conseils: "Mettez en avant votre aisance relationnelle, votre connaissance des produits et votre capacite a atteindre les objectifs de vente. Les recruteurs en commerce cherchent des candidats motives et orientes client.", exemples: "Vendeuse en pret-a-porter, vendeur en magasin, conseiller de vente, vendeur en boulangerie, vendeuse en parfumerie" },
  "stage": { titre: "Stage", secteur: "Formation et insertion", desc: "Vous cherchez un stage ? Notre IA redige une lettre de motivation qui valorise votre formation, votre motivation et vos competences, meme sans experience professionnelle.", conseils: "Insistez sur votre envie d'apprendre, vos projets scolaires pertinents et ce que vous pouvez apporter a l'entreprise. Un stagiaire motive vaut plus qu'un CV rempli.", exemples: "Stage de 3eme, stage BTS, stage licence, stage master, stage de fin d'etudes, stage en entreprise" },
  "alternance": { titre: "Alternance", secteur: "Formation en entreprise", desc: "Vous postulez en alternance ? Notre IA cree une lettre qui montre votre double competence : formation theorique et motivation pour l'entreprise.", conseils: "Expliquez clairement votre rythme d'alternance, votre formation et pourquoi cette entreprise vous interesse. Montrez que vous etes operationnel rapidement.", exemples: "Alternance BTS MCO, alternance licence pro, alternance master, contrat d'apprentissage, contrat de professionnalisation" },
  "infirmiere": { titre: "Infirmiere / Infirmier", secteur: "Sante et medical", desc: "Vous postulez comme infirmiere ou infirmier ? Notre IA genere une lettre professionnelle adaptee au secteur medical, mettant en avant vos competences soignantes.", conseils: "Valorisez vos stages hospitaliers, votre empathie, votre rigueur et votre capacite a travailler en equipe pluridisciplinaire. Le secteur de la sante recrute massivement.", exemples: "Infirmiere en hopital, infirmier liberal, infirmiere en EHPAD, infirmier en bloc operatoire, infirmiere scolaire" },
  "sans-experience": { titre: "Sans experience", secteur: "Premier emploi", desc: "Pas d'experience ? Pas de probleme. Notre IA redige une lettre de motivation convaincante qui met en avant vos qualites, votre motivation et votre potentiel.", conseils: "Concentrez-vous sur vos qualites personnelles, vos activites extra-scolaires, votre benevolat ou vos projets personnels. Chaque experience de vie compte.", exemples: "Premier emploi, job etudiant, candidature sans experience, debutant, jeune diplome sans experience" },
  "reconversion": { titre: "Reconversion professionnelle", secteur: "Changement de carriere", desc: "Vous changez de carriere ? Notre IA cree une lettre qui transforme votre reconversion en atout, en valorisant vos competences transferables.", conseils: "Expliquez votre motivation pour ce changement, les competences de votre ancien metier qui sont utiles dans le nouveau, et votre formation recente.", exemples: "Reconversion apres licenciement, changement de secteur, retour a l'emploi, reconversion apres burn-out, nouvelle carriere" },
  "aide-soignante": { titre: "Aide-soignante / Aide-soignant", secteur: "Sante et medical", desc: "Vous postulez comme aide-soignante ? Notre IA redige une lettre adaptee au secteur du soin, mettant en avant votre bienveillance et vos competences.", conseils: "Mettez en avant votre formation DEAS, vos stages, votre patience et votre capacite a accompagner les patients au quotidien.", exemples: "Aide-soignante en EHPAD, aide-soignant en hopital, aide-soignante a domicile, aide-soignant en clinique" },
  "commercial": { titre: "Commercial(e)", secteur: "Vente et business", desc: "Vous postulez comme commercial ? Notre IA genere une lettre percutante qui met en avant votre force de persuasion et vos resultats.", conseils: "Chiffrez vos resultats : chiffre d'affaires genere, nombre de clients signes, objectifs depasses. Les recruteurs veulent des preuves concretes.", exemples: "Commercial terrain, commercial sedentaire, technico-commercial, commercial B2B, attache commercial, ingenieur commercial" },
  "job-ete": { titre: "Job d'ete", secteur: "Emploi saisonnier", desc: "Vous cherchez un job d'ete ? Notre IA cree une lettre courte et efficace, parfaite pour les emplois saisonniers en restauration, commerce ou tourisme.", conseils: "Soyez direct : indiquez vos disponibilites, votre motivation et votre capacite a etre operationnel rapidement. Pour un job d'ete, la disponibilite compte autant que l'experience.", exemples: "Serveur en restaurant, caissier, animateur de centre de loisirs, vendeur saisonnier, employe de plage" },
  "candidature-spontanee": { titre: "Candidature spontanee", secteur: "Tous secteurs", desc: "Vous envoyez une candidature spontanee ? Notre IA redige une lettre qui capte l'attention du recruteur, meme sans offre d'emploi publiee.", conseils: "Montrez que vous connaissez l'entreprise, expliquez pourquoi elle vous interesse specifiquement et ce que vous pouvez lui apporter concretement.", exemples: "Candidature spontanee grande entreprise, candidature spontanee PME, candidature spontanee start-up, prospection emploi" },
  "serveur": { titre: "Serveur / Serveuse", secteur: "Restauration", desc: "Vous postulez comme serveur ou serveuse ? Notre IA genere une lettre qui met en valeur votre sens du service, votre rapidite et votre sourire.", conseils: "La restauration recrute massivement. Mettez en avant votre resistance au stress, votre polyvalence et votre experience client.", exemples: "Serveur en restaurant, serveuse en brasserie, barman, serveur en hotel, serveuse en cafe" },
  "comptable": { titre: "Comptable", secteur: "Finance et gestion", desc: "Vous postulez comme comptable ? Notre IA cree une lettre professionnelle qui met en avant votre rigueur et vos competences techniques.", conseils: "Mentionnez vos diplomes (BTS CG, DCG, DSCG), les logiciels maitrises (Sage, Cegid, Excel avance) et votre experience en cabinet ou entreprise.", exemples: "Comptable en cabinet, comptable en entreprise, aide-comptable, comptable fournisseurs, chef comptable" },
  "assistant-administratif": { titre: "Assistant(e) administratif(ve)", secteur: "Administration", desc: "Vous postulez comme assistant administratif ? Notre IA redige une lettre qui valorise votre organisation et votre polyvalence.", conseils: "Les recruteurs cherchent des profils organises, autonomes et maitrisant le Pack Office. Mentionnez votre experience en gestion administrative et accueil.", exemples: "Assistante de direction, assistant administratif, secretaire, assistante RH, assistant de gestion" },
  "developpeur": { titre: "Developpeur / Developpeuse", secteur: "Informatique et tech", desc: "Vous postulez comme developpeur ? Notre IA genere une lettre technique et personnalisee, adaptee au monde de la tech.", conseils: "Mentionnez vos langages de programmation, vos projets concrets (GitHub, portfolio), et votre veille technologique.", exemples: "Developpeur web, developpeur mobile, developpeur full-stack, developpeur front-end, developpeur Python" },
  "agent-dentretien": { titre: "Agent d'entretien", secteur: "Nettoyage et hygiene", desc: "Vous postulez comme agent d'entretien ? Notre IA cree une lettre professionnelle qui met en avant votre serieux et votre ponctualite.", conseils: "Mettez en avant votre fiabilite, votre connaissance des produits et techniques de nettoyage, et votre capacite a respecter les consignes.", exemples: "Agent d'entretien en entreprise, agent de proprete, femme de menage, agent hospitalier" },
  "chauffeur-livreur": { titre: "Chauffeur-livreur", secteur: "Transport et logistique", desc: "Vous postulez comme chauffeur-livreur ? Notre IA redige une lettre qui met en avant votre permis, votre ponctualite et votre sens de l'orientation.", conseils: "Indiquez votre type de permis (B, C), votre connaissance de la zone geographique et votre experience en livraison. La ponctualite est cle.", exemples: "Chauffeur-livreur Amazon, livreur Uber Eats, chauffeur poids lourd, livreur de colis, chauffeur VTC" },
  "boulanger": { titre: "Boulanger / Boulangere", secteur: "Artisanat et alimentation", desc: "Vous postulez comme boulanger ? Notre IA genere une lettre qui met en avant votre savoir-faire artisanal et votre passion du metier.", conseils: "Parlez de votre formation (CAP boulangerie), de votre maitrise des techniques de panification et de votre capacite a travailler en horaires decales.", exemples: "Boulanger artisanal, boulanger en grande surface, patissier-boulanger, apprenti boulanger" },
  "caissier": { titre: "Caissier / Caissiere", secteur: "Commerce et distribution", desc: "Vous postulez comme caissier ou caissiere ? Notre IA cree une lettre qui met en avant votre rigueur, votre rapidite et votre sens du contact.", conseils: "Montrez votre aisance avec la manipulation de caisse, votre politesse et votre capacite a gerer les files d'attente avec le sourire.", exemples: "Caissiere en supermarche, caissier en magasin, hotesse de caisse, employe libre-service" },
  "cuisinier": { titre: "Cuisinier / Cuisiniere", secteur: "Restauration", desc: "Vous postulez comme cuisinier ? Notre IA redige une lettre qui met en valeur votre creativite culinaire et votre rigueur en cuisine.", conseils: "Decrivez vos specialites, votre formation (CAP cuisine, BEP), vos experiences en restaurant et votre capacite a travailler sous pression.", exemples: "Cuisinier en restaurant, chef de partie, commis de cuisine, cuisinier en collectivite, chef cuisinier" },
  "educateur-specialise": { titre: "Educateur specialise", secteur: "Social et educatif", desc: "Vous postulez comme educateur specialise ? Notre IA genere une lettre adaptee au secteur social, mettant en avant votre empathie et votre engagement.", conseils: "Valorisez votre diplome DEES, vos stages en structure medico-sociale et votre capacite a accompagner des publics en difficulte.", exemples: "Educateur en foyer, educateur de rue, educateur PJJ, moniteur-educateur, educateur en IME" },
  "electricien": { titre: "Electricien", secteur: "BTP et artisanat", desc: "Vous postulez comme electricien ? Notre IA cree une lettre technique qui met en avant vos habilitations et votre experience terrain.", conseils: "Mentionnez vos habilitations electriques (BR, B1V, B2V), votre CAP/BEP et votre experience en chantier ou maintenance.", exemples: "Electricien du batiment, electricien industriel, electricien auto-entrepreneur, technicien electricien" },
  "hotesse-daccueil": { titre: "Hotesse d'accueil / Hote d'accueil", secteur: "Accueil et relation client", desc: "Vous postulez comme hotesse d'accueil ? Notre IA redige une lettre qui met en avant votre presentation, votre sourire et votre professionnalisme.", conseils: "Les recruteurs cherchent une excellente presentation, la maitrise de langues etrangeres et un sens aigu du service client.", exemples: "Hotesse d'accueil en entreprise, hote d'accueil evenementiel, standardiste, receptionniste" },
  "ingenieur": { titre: "Ingenieur", secteur: "Ingenierie et technique", desc: "Vous postulez comme ingenieur ? Notre IA genere une lettre professionnelle adaptee aux exigences du monde de l'ingenierie.", conseils: "Mettez en avant votre ecole d'ingenieur, vos projets techniques, vos competences specifiques et votre capacite a resoudre des problemes complexes.", exemples: "Ingenieur informatique, ingenieur mecanique, ingenieur civil, ingenieur agronome, ingenieur commercial" },
  "manutentionnaire": { titre: "Manutentionnaire", secteur: "Logistique et entreposage", desc: "Vous postulez comme manutentionnaire ? Notre IA cree une lettre qui met en avant votre endurance physique et votre serieux.", conseils: "Indiquez si vous avez le CACES, votre experience en entrepot et votre capacite a respecter les consignes de securite.", exemples: "Manutentionnaire en entrepot, preparateur de commandes, cariste, agent logistique, magasinier" },
  "mecanicien": { titre: "Mecanicien / Mecanicienne", secteur: "Automobile et maintenance", desc: "Vous postulez comme mecanicien ? Notre IA redige une lettre technique qui met en avant vos competences en diagnostic et reparation.", conseils: "Decrivez vos certifications, les marques sur lesquelles vous avez travaille et votre maitrise des outils de diagnostic.", exemples: "Mecanicien automobile, mecanicien poids lourd, mecanicien moto, technicien de maintenance, mecanicien aeronautique" },
  "pharmacien": { titre: "Pharmacien / Pharmacienne", secteur: "Sante et pharmacie", desc: "Vous postulez comme pharmacien ? Notre IA genere une lettre adaptee au secteur pharmaceutique, mettant en avant votre expertise scientifique.", conseils: "Valorisez votre diplome de docteur en pharmacie, vos stages officinaux, votre connaissance des medicaments et votre sens du conseil patient.", exemples: "Pharmacien d'officine, pharmacien hospitalier, pharmacien en industrie, preparateur en pharmacie" },
  "plombier": { titre: "Plombier", secteur: "BTP et artisanat", desc: "Vous postulez comme plombier ? Notre IA cree une lettre qui met en avant votre savoir-faire technique et votre experience terrain.", conseils: "Mentionnez vos qualifications (CAP installateur sanitaire), votre experience en depannage et installation, et votre autonomie.", exemples: "Plombier chauffagiste, plombier sanitaire, plombier depanneur, technicien plombier" },
  "professeur": { titre: "Professeur / Enseignant", secteur: "Education et formation", desc: "Vous postulez comme professeur ? Notre IA redige une lettre qui met en valeur votre pedagogie et votre passion pour l'enseignement.", conseils: "Parlez de votre approche pedagogique, vos diplomes (CAPES, Agreg, Master MEEF) et votre capacite a adapter votre enseignement aux eleves.", exemples: "Professeur des ecoles, professeur de mathematiques, professeur de francais, enseignant contractuel, formateur" },
  "secretaire": { titre: "Secretaire", secteur: "Administration et bureau", desc: "Vous postulez comme secretaire ? Notre IA genere une lettre qui met en avant votre organisation, votre discretion et votre maitrise bureautique.", conseils: "Mettez en avant votre maitrise de Word, Excel, PowerPoint, votre rapidite de frappe et votre capacite a gerer les agendas et les appels.", exemples: "Secretaire medicale, secretaire juridique, secretaire de direction, secretaire comptable, secretaire administrative" },
  "technicien-informatique": { titre: "Technicien informatique", secteur: "Informatique et support", desc: "Vous postulez comme technicien informatique ? Notre IA cree une lettre qui met en avant vos competences en support et maintenance.", conseils: "Decrivez vos certifications (CompTIA, ITIL), votre experience en helpdesk et votre maitrise des systemes Windows, Linux et reseaux.", exemples: "Technicien helpdesk, technicien reseau, technicien systemes, administrateur informatique, support IT" },
  "agent-immobilier": { titre: "Agent immobilier", secteur: "Immobilier", desc: "Vous postulez comme agent immobilier ? Notre IA redige une lettre commerciale qui met en avant votre talent de negociateur.", conseils: "Montrez votre connaissance du marche local, votre reseau, vos resultats en vente et votre carte professionnelle ou formation.", exemples: "Agent immobilier en agence, negociateur immobilier, conseiller immobilier, mandataire independant" },
  "animateur": { titre: "Animateur / Animatrice", secteur: "Animation et loisirs", desc: "Vous postulez comme animateur ? Notre IA genere une lettre dynamique qui met en avant votre creativite et votre energie.", conseils: "Parlez de votre BAFA/BAFD, vos experiences en centre de loisirs, colonies de vacances et votre capacite a encadrer des groupes.", exemples: "Animateur centre de loisirs, animateur periscolaire, animateur colonie, animateur sportif, animateur EHPAD" },
  "assistant-maternel": { titre: "Assistante maternelle", secteur: "Petite enfance", desc: "Vous postulez comme assistante maternelle ? Notre IA cree une lettre bienveillante qui met en avant votre amour des enfants.", conseils: "Valorisez votre agrement, votre formation petite enfance, votre patience et votre capacite a creer un environnement securisant.", exemples: "Assistante maternelle agreee, nounou, garde d'enfants a domicile, auxiliaire parentale" },
  "auxiliaire-de-vie": { titre: "Auxiliaire de vie", secteur: "Aide a la personne", desc: "Vous postulez comme auxiliaire de vie ? Notre IA redige une lettre humaine qui met en avant votre devouement et votre empathie.", conseils: "Mettez en avant votre DEAVS ou mention complementaire, votre experience avec les personnes agees ou handicapees et votre patience.", exemples: "Auxiliaire de vie a domicile, aide a domicile, accompagnant educatif et social, auxiliaire de vie scolaire" },
  "coiffeur": { titre: "Coiffeur / Coiffeuse", secteur: "Beaute et esthetique", desc: "Vous postulez comme coiffeur ou coiffeuse ? Notre IA genere une lettre creative qui met en avant votre talent et votre sens artistique.", conseils: "Parlez de votre CAP/BP coiffure, vos specialites (coloration, coupe homme, chignon), et votre sens du conseil client.", exemples: "Coiffeuse en salon, coiffeur a domicile, barbier, coiffeuse coloriste, manager de salon" },
  "conducteur-de-bus": { titre: "Conducteur de bus", secteur: "Transport en commun", desc: "Vous postulez comme conducteur de bus ? Notre IA cree une lettre qui met en avant votre sens des responsabilites et votre permis D.", conseils: "Mentionnez votre permis D, votre FIMO voyageurs, votre ponctualite et votre sens du service aux voyageurs.", exemples: "Conducteur de bus urbain, conducteur de car scolaire, conducteur de navette, chauffeur de bus touristique" },
  "gestionnaire-de-paie": { titre: "Gestionnaire de paie", secteur: "Ressources humaines", desc: "Vous postulez comme gestionnaire de paie ? Notre IA redige une lettre technique mettant en avant votre rigueur et vos competences.", conseils: "Mentionnez votre maitrise des logiciels de paie (Sage, Cegid, Silae), votre connaissance du droit social et votre precision.", exemples: "Gestionnaire de paie en cabinet, gestionnaire de paie en entreprise, technicien paie, assistant paie" },
  "graphiste": { titre: "Graphiste / Designer", secteur: "Creation et design", desc: "Vous postulez comme graphiste ? Notre IA genere une lettre creative qui met en avant votre univers visuel et vos competences techniques.", conseils: "Mentionnez votre portfolio, vos outils (Photoshop, Illustrator, Figma, InDesign) et vos projets les plus marquants.", exemples: "Graphiste freelance, directeur artistique, webdesigner, UX designer, infographiste, maquettiste" },
  "logisticien": { titre: "Logisticien", secteur: "Supply chain et logistique", desc: "Vous postulez comme logisticien ? Notre IA cree une lettre qui met en avant votre sens de l'organisation et votre maitrise des flux.", conseils: "Parlez de votre experience en gestion de stock, votre maitrise des ERP (SAP, WMS) et votre capacite a optimiser les couts logistiques.", exemples: "Responsable logistique, coordinateur supply chain, gestionnaire de stock, approvisionneur, chef de quai" },
  "opticien": { titre: "Opticien / Opticienne", secteur: "Sante et optique", desc: "Vous postulez comme opticien ? Notre IA redige une lettre qui allie competences techniques et sens commercial.", conseils: "Valorisez votre BTS opticien-lunetier, votre maitrise des examens de vue, votre sens du conseil et votre experience en vente.", exemples: "Opticien en magasin, opticien independant, responsable magasin optique, opticien contactologue" },
  "paysagiste": { titre: "Paysagiste / Jardinier", secteur: "Espaces verts", desc: "Vous postulez comme paysagiste ? Notre IA genere une lettre qui met en avant votre amour de la nature et votre savoir-faire.", conseils: "Decrivez vos competences en amenagement paysager, entretien des espaces verts, connaissance des vegetaux et utilisation des machines.", exemples: "Jardinier paysagiste, ouvrier paysagiste, chef d'equipe espaces verts, elagueur, pepinieriste" },
  "preparateur-de-commandes": { titre: "Preparateur de commandes", secteur: "Logistique et entreposage", desc: "Vous postulez comme preparateur de commandes ? Notre IA cree une lettre efficace qui met en avant votre rapidite et votre precision.", conseils: "Mentionnez votre CACES si vous l'avez, votre experience en entrepot, votre rapidite et votre rigueur dans la preparation.", exemples: "Preparateur de commandes en entrepot, picker, agent logistique, preparateur drive, preparateur e-commerce" },
  "receptionniste": { titre: "Receptionniste", secteur: "Hotellerie et accueil", desc: "Vous postulez comme receptionniste ? Notre IA redige une lettre qui met en avant votre sens de l'accueil et vos langues etrangeres.", conseils: "Les hotels cherchent des profils bilingues ou trilingues, souriants et maitrisant les logiciels de reservation (Opera, Mews).", exemples: "Receptionniste d'hotel, night auditor, concierge, agent de reservation, receptionniste de camping" },
  "responsable-marketing": { titre: "Responsable marketing", secteur: "Marketing et communication", desc: "Vous postulez comme responsable marketing ? Notre IA genere une lettre strategique qui met en avant votre vision et vos resultats.", conseils: "Chiffrez vos resultats (ROI, taux de conversion, croissance), mentionnez vos competences digitales et votre experience en gestion d'equipe.", exemples: "Responsable marketing digital, chef de produit, brand manager, responsable communication, growth manager" },
  "sage-femme": { titre: "Sage-femme", secteur: "Sante et maternite", desc: "Vous postulez comme sage-femme ? Notre IA cree une lettre professionnelle adaptee au monde de la naissance et de la sante feminine.", conseils: "Valorisez votre diplome d'Etat, vos stages en maternite, votre expertise en suivi de grossesse et accouchement.", exemples: "Sage-femme en maternite, sage-femme liberale, sage-femme en PMI, sage-femme echographiste" },
  "technicien-de-maintenance": { titre: "Technicien de maintenance", secteur: "Industrie et maintenance", desc: "Vous postulez comme technicien de maintenance ? Notre IA redige une lettre technique qui met en avant vos competences en depannage.", conseils: "Decrivez vos habilitations, vos competences en mecanique, electrique et automatisme, et votre capacite a intervenir rapidement.", exemples: "Technicien de maintenance industrielle, technicien SAV, technicien CVC, technicien de maintenance batiment" },
  "vendeur-automobile": { titre: "Vendeur automobile", secteur: "Automobile et vente", desc: "Vous postulez comme vendeur automobile ? Notre IA genere une lettre commerciale qui met en avant votre passion auto et vos talents de negociateur.", conseils: "Montrez votre connaissance des marques, votre experience en negociation et vos resultats de vente. La passion automobile fait la difference.", exemples: "Vendeur en concession, conseiller commercial automobile, vendeur VO, vendeur VN, responsable de parc" },
  "veterinaire": { titre: "Veterinaire", secteur: "Sante animale", desc: "Vous postulez comme veterinaire ? Notre IA cree une lettre professionnelle qui met en avant votre expertise medicale et votre amour des animaux.", conseils: "Valorisez votre diplome de docteur veterinaire, vos stages en clinique, vos specialites et votre capacite a communiquer avec les proprietaires.", exemples: "Veterinaire en clinique, veterinaire rural, veterinaire NAC, veterinaire equin, assistant veterinaire" },
  "webmaster": { titre: "Webmaster / Chef de projet web", secteur: "Digital et web", desc: "Vous postulez comme webmaster ? Notre IA redige une lettre qui met en avant votre polyvalence technique et votre vision web.", conseils: "Mentionnez vos competences en HTML/CSS, CMS (WordPress, Shopify), SEO, analytics et votre capacite a gerer un site de A a Z.", exemples: "Webmaster, chef de projet digital, responsable de site web, community manager, traffic manager" },
  "parcoursup": { titre: "Parcoursup", secteur: "Orientation post-bac", desc: "Vous redigez votre lettre de motivation Parcoursup ? Notre IA vous aide a formuler un projet de formation motive et convaincant.", conseils: "Expliquez votre projet professionnel, pourquoi cette formation vous correspond, vos resultats scolaires pertinents et vos activites extra-scolaires.", exemples: "Licence de droit, BTS commerce, classe preparatoire, ecole d'ingenieur, IUT informatique, PASS medecine" },
}

const SITE = "https://lettredemotivation-ia.fr"

export async function getStaticPaths() {
  const paths = Object.keys(METIERS).map(slug => ({ params: { metier: `lettre-de-motivation-${slug}` } }))
  return { paths, fallback: false }
}

export async function getStaticProps({ params }) {
  const slug = params.metier.replace("lettre-de-motivation-", "")
  const data = METIERS[slug] || null
  if (!data) return { notFound: true }
  return { props: { slug, ...data } }
}

export default function PageMetier({ slug, titre, secteur, desc, conseils, exemples }) {
  const font = "'Instrument Serif', Georgia, serif"
  const sans = "'DM Sans', system-ui, sans-serif"
  const green = "#059669"
  const blue = "#2563eb"

  return (
    <>
      <Head>
        <title>{`Lettre de motivation ${titre} - Generateur IA gratuit | lettredemotivation-ia.fr`}</title>
        <meta name="description" content={`Generez votre lettre de motivation ${titre.toLowerCase()} en 30 secondes avec l'IA. Personnalisee, aux normes francaises, gratuite.`} />
        <meta property="og:title" content={`Lettre de motivation ${titre} - IA`} />
        <meta property="og:description" content={desc} />
        <meta property="og:url" content={`${SITE}/lettre-de-motivation-${slug}`} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet" />
      </Head>

      <div style={{ fontFamily: sans, color: "#1e293b", background: "#fff", minHeight: "100vh" }}>

        {/* Nav */}
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "24px 24px 0" }}>
          <a href="/" style={{ display: "inline-flex", alignItems: "center", cursor: "pointer", border: "1.5px solid #1e293b", borderRadius: 8, padding: "8px 16px", gap: 8, textDecoration: "none" }}>
            <span style={{ fontSize: 14, fontWeight: 600, color: "#1e293b", textTransform: "uppercase", letterSpacing: 2 }}>Lettre de motivation</span>
            <span style={{ width: 1.5, height: 18, background: "#94a3b8", opacity: 0.3 }} />
            <span style={{ fontSize: 16, fontWeight: 700, letterSpacing: 3, background: `linear-gradient(135deg, ${green}, ${blue})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>IA</span>
          </a>
        </div>

        {/* Hero */}
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px" }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: green, textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>{secteur}</div>
          <h1 style={{ fontFamily: font, fontSize: 40, fontWeight: 400, lineHeight: 1.15, letterSpacing: -1, marginBottom: 20, color: "#1e293b" }}>
            Lettre de motivation<br />
            <span style={{ fontStyle: "italic", background: `linear-gradient(135deg, ${green}, ${blue})`, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{titre}</span>
          </h1>
          <p style={{ fontSize: 17, lineHeight: 1.7, color: "#64748b", marginBottom: 32, maxWidth: 560 }}>{desc}</p>
          <a href="/" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "14px 32px", borderRadius: 10, background: `linear-gradient(135deg, ${green}, ${blue})`, color: "#fff", fontSize: 15, fontWeight: 500, textDecoration: "none", boxShadow: "0 8px 32px rgba(5,150,105,0.2)" }}>
            Generer ma lettre gratuitement
          </a>
        </div>

        {/* Conseils */}
        <div style={{ background: "#f5f7fa", padding: "56px 0" }}>
          <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px" }}>
            <h2 style={{ fontSize: 22, fontWeight: 700, textTransform: "uppercase", letterSpacing: 2, marginBottom: 20, color: "#1e293b" }}>
              Nos conseils pour votre lettre
            </h2>
            <p style={{ fontSize: 16, lineHeight: 1.8, color: "#475569", marginBottom: 24 }}>{conseils}</p>
            <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.06)", borderRadius: 12, padding: "20px 24px" }}>
              <div style={{ fontSize: 13, fontWeight: 600, color: green, textTransform: "uppercase", letterSpacing: 1, marginBottom: 8 }}>Postes concernes</div>
              <p style={{ fontSize: 14, lineHeight: 1.7, color: "#64748b", margin: 0 }}>{exemples}</p>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div style={{ background: `linear-gradient(135deg, ${green}, #047857, #0f766e)`, padding: "56px 0" }}>
          <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px", textAlign: "center" }}>
            <h2 style={{ fontSize: 22, fontWeight: 700, color: "#fff", textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>Pret a creer votre lettre ?</h2>
            <p style={{ fontSize: 15, color: "rgba(255,255,255,0.75)", lineHeight: 1.7, maxWidth: 420, margin: "0 auto 28px" }}>2 lettres gratuites, aucune carte bancaire. L'IA redige votre lettre {titre.toLowerCase()} en 30 secondes.</p>
            <a href="/" style={{ display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "14px 32px", borderRadius: 10, background: "#fff", color: green, fontSize: 15, fontWeight: 600, textDecoration: "none", boxShadow: "0 8px 32px rgba(0,0,0,0.15)" }}>
              Generer ma lettre maintenant
            </a>
          </div>
        </div>

        {/* Footer */}
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "32px 24px", textAlign: "center" }}>
          <p style={{ fontSize: 12, color: "#94a3b8" }}>lettredemotivation-ia.fr - Generateur de lettres de motivation par intelligence artificielle</p>
        </div>
      </div>
    </>
  )
}
