import Head from 'next/head'

const sans = `'Montserrat', system-ui, sans-serif`;
const T = {
  bg: "#ffffff", text: "#1e293b", textMuted: "#64748b", textDim: "#94a3b8",
  accent: "#059669", blue: "#2563eb", border: "rgba(0,0,0,0.06)",
  green: "#059669", greenSoft: "rgba(5,150,105,0.07)", accentBorder: "rgba(5,150,105,0.18)",
  blueSoft: "rgba(37,99,235,0.06)", blueBorder: "rgba(37,99,235,0.12)",
};

const M = {
  "vendeuse": { t: "Vendeuse / Vendeur", s: "Commerce et vente", d: "Vous postulez comme vendeuse ou vendeur ? Notre IA genere une lettre de motivation personnalisee qui met en valeur votre sens du contact client et votre dynamisme.", c: "Mettez en avant votre aisance relationnelle, votre connaissance des produits et votre capacite a atteindre les objectifs de vente.", ex: "Vendeuse en pret-a-porter, vendeur en magasin, conseiller de vente, vendeur en boulangerie, vendeuse en parfumerie", phrases: ["Mon experience de 2 ans en vente m'a appris a identifier rapidement les besoins des clients.", "Ma connaissance approfondie des techniques de merchandising me permet d'optimiser les ventes.", "Mon dynamisme et mon sens du contact font de moi une vendeuse efficace et appreciee."], faq: [["Faut-il mentionner son chiffre d'affaires ?", "Oui, si vous avez des resultats chiffres, mentionnez-les. Les recruteurs adorent les preuves concretes."], ["Quelle longueur pour une lettre vendeuse ?", "250 a 350 mots suffisent. Soyez concis et percutant, comme en vente."], ["Comment se demarquer sans experience ?", "Mettez en avant vos qualites relationnelles, un job etudiant ou du benevolat impliquant du contact client."]], temoignage: { nom: "Sarah K.", poste: "Embauchee chez Zara", texte: "J'ai genere ma lettre en 30 secondes et j'ai ete appelee pour un entretien 2 jours apres !" } },
  "stage": { t: "Stage", s: "Formation et insertion", d: "Vous cherchez un stage ? Notre IA redige une lettre de motivation qui valorise votre formation, votre motivation et vos competences.", c: "Insistez sur votre envie d'apprendre, vos projets scolaires pertinents et ce que vous pouvez apporter a l'entreprise.", ex: "Stage de 3eme, stage BTS, stage licence, stage master, stage de fin d'etudes", phrases: ["Actuellement en [formation], je recherche un stage de [duree] pour mettre en pratique mes connaissances.", "Mon projet professionnel s'oriente vers [domaine], c'est pourquoi votre entreprise m'interesse particulierement.", "Rigoureux et motive, je souhaite contribuer activement a vos projets."], faq: [["Comment ecrire une lettre de stage sans experience ?", "Focalisez-vous sur votre formation, vos projets scolaires et votre motivation."], ["Quelle longueur pour une lettre de stage ?", "150 a 250 mots. Les recruteurs de stagiaires lisent vite, allez a l'essentiel."], ["Faut-il personnaliser pour chaque entreprise ?", "Absolument ! Mentionnez le nom de l'entreprise et expliquez pourquoi elle vous interesse."]], temoignage: { nom: "Lucas M.", poste: "Stage chez L'Oreal", texte: "Ma lettre generee par l'IA etait tellement bien ecrite que mon maitre de stage l'a complimentee !" } },
  "alternance": { t: "Alternance", s: "Formation en entreprise", d: "Vous postulez en alternance ? Notre IA cree une lettre qui montre votre double competence : formation theorique et motivation pour l'entreprise.", c: "Expliquez clairement votre rythme d'alternance, votre formation et pourquoi cette entreprise vous interesse.", ex: "Alternance BTS MCO, alternance licence pro, alternance master, contrat d'apprentissage", phrases: ["En preparation de mon [diplome], je recherche une alternance au rythme de [rythme].", "L'alternance represente pour moi l'opportunite ideale de combiner theorie et pratique.", "Operationnel des ma prise de poste, je m'investirai pleinement dans vos projets."], faq: [["Faut-il preciser le rythme d'alternance ?", "Oui, c'est essentiel. L'entreprise doit savoir quand vous serez present."], ["Comment convaincre sans experience ?", "Votre formation est votre force. Montrez que vous apportez des connaissances fraiches."], ["Lettre pour l'ecole ou l'entreprise ?", "Les deux ! Notre IA adapte la lettre selon le destinataire."]], temoignage: { nom: "Emma R.", poste: "Alternance BTS MCO", texte: "3 candidatures envoyees avec la lettre IA, 2 entretiens obtenus. Je recommande a 100% !" } },
  "infirmiere": { t: "Infirmiere / Infirmier", s: "Sante et medical", d: "Vous postulez comme infirmiere ou infirmier ? Notre IA genere une lettre professionnelle adaptee au secteur medical.", c: "Valorisez vos stages hospitaliers, votre empathie, votre rigueur et votre capacite a travailler en equipe.", ex: "Infirmiere en hopital, infirmier liberal, infirmiere en EHPAD, infirmier en bloc operatoire", phrases: ["Diplomee d'Etat depuis [annee], j'ai developpe une expertise en soins [specialite].", "Ma rigueur et mon empathie me permettent d'accompagner les patients avec professionnalisme.", "Mon experience en equipe pluridisciplinaire est un atout pour votre etablissement."], faq: [["Faut-il mentionner ses stages ?", "Oui, detaillez vos stages hospitaliers et les services dans lesquels vous avez travaille."], ["Comment se demarquer dans le medical ?", "Mentionnez vos specialites, formations complementaires et votre approche du soin."], ["Lettre manuscrite ou numerique ?", "En 2025, la lettre numerique est la norme, meme dans le medical."]], temoignage: { nom: "Julie P.", poste: "Infirmiere au CHU", texte: "La lettre etait parfaitement adaptee au monde hospitalier. J'ai ete recrutee en CDI !" } },
  "sans-experience": { t: "Sans experience", s: "Premier emploi", d: "Pas d'experience ? Pas de probleme. Notre IA redige une lettre convaincante qui met en avant vos qualites et votre potentiel.", c: "Concentrez-vous sur vos qualites personnelles, vos activites extra-scolaires et vos projets personnels.", ex: "Premier emploi, job etudiant, candidature sans experience, debutant, jeune diplome", phrases: ["Bien que debutant, ma determination et ma capacite d'apprentissage rapide sont mes meilleurs atouts.", "Mon parcours m'a permis de developper des qualites essentielles : rigueur, ponctualite et esprit d'equipe.", "Je suis convaincu que ma motivation compensera largement mon manque d'experience."], faq: [["Comment postuler sans aucune experience ?", "Mettez en avant vos etudes, vos qualites humaines, votre benevolat ou vos activites extra-scolaires."], ["Les recruteurs acceptent-ils les debutants ?", "Oui ! De nombreux postes sont ouverts aux debutants."], ["Faut-il mentionner ses loisirs ?", "Si vos loisirs demontrent des qualites utiles pour le poste, oui."]], temoignage: { nom: "Amine B.", poste: "Premier emploi en logistique", texte: "Sans experience, j'avais du mal a ecrire. L'IA a su mettre en valeur mes qualites !" } },
  "reconversion": { t: "Reconversion professionnelle", s: "Changement de carriere", d: "Vous changez de carriere ? Notre IA cree une lettre qui transforme votre reconversion en atout.", c: "Expliquez votre motivation pour ce changement et les competences transferables de votre ancien metier.", ex: "Reconversion apres licenciement, changement de secteur, retour a l'emploi, nouvelle carriere", phrases: ["Apres [X] annees dans [ancien secteur], j'ai choisi de me reconvertir vers [nouveau secteur].", "Les competences acquises dans mon precedent poste sont directement transferables.", "Ma reconversion est le fruit d'une reflexion murie et d'une formation adaptee."], faq: [["Comment expliquer sa reconversion ?", "Soyez positif : parlez de ce qui vous attire dans le nouveau metier."], ["Faut-il mentionner sa formation ?", "Oui, c'est essentiel pour prouver votre serieux."], ["Les recruteurs voient-ils la reconversion positivement ?", "De plus en plus ! Cela montre du courage et de l'adaptabilite."]], temoignage: { nom: "Nathalie D.", poste: "De comptable a educatrice", texte: "L'IA a su expliquer ma reconversion de maniere positive !" } },
  "aide-soignante": { t: "Aide-soignante / Aide-soignant", s: "Sante et medical", d: "Vous postulez comme aide-soignante ? Notre IA redige une lettre adaptee au secteur du soin.", c: "Mettez en avant votre formation DEAS, vos stages, votre patience et votre bienveillance.", ex: "Aide-soignante en EHPAD, aide-soignant en hopital, aide-soignante a domicile", phrases: ["Titulaire du DEAS, j'ai acquis une solide experience aupres des personnes agees.", "Ma bienveillance et mon ecoute me permettent d'etablir une relation de confiance.", "Je maitrise les gestes de soins quotidiens et les protocoles d'hygiene."], faq: [["Le DEAS est-il obligatoire ?", "Oui, il est requis pour exercer."], ["Comment se demarquer ?", "Parlez de vos stages et de votre approche humaine."], ["Faut-il une lettre longue ?", "Non, 200 a 300 mots suffisent."]], temoignage: { nom: "Fatima A.", poste: "Aide-soignante en EHPAD", texte: "Recrutee en 1 semaine !" } },
  "commercial": { t: "Commercial(e)", s: "Vente et business", d: "Vous postulez comme commercial ? Notre IA genere une lettre percutante qui met en avant vos resultats.", c: "Chiffrez vos resultats : CA genere, clients signes, objectifs depasses.", ex: "Commercial terrain, commercial sedentaire, technico-commercial, commercial B2B", phrases: ["En 3 ans, j'ai developpe un portefeuille de [X] clients et genere [X]k euros de CA.", "Ma capacite a identifier les besoins clients est mon principal atout.", "Oriente resultats, je depasse regulierement mes objectifs."], faq: [["Faut-il chiffrer ses resultats ?", "Absolument !"], ["Lettre courte ou longue ?", "Courte et percutante, 250 mots max."], ["Comment postuler sans experience ?", "Mettez en avant toute experience de vente."]], temoignage: { nom: "Thomas L.", poste: "Commercial B2B", texte: "Entretien obtenu le lendemain !" } },
  "job-ete": { t: "Job d'ete", s: "Emploi saisonnier", d: "Vous cherchez un job d'ete ? Notre IA cree une lettre courte et efficace pour les emplois saisonniers.", c: "Indiquez vos disponibilites, votre motivation et votre capacite a etre operationnel rapidement.", ex: "Serveur, caissier, animateur, vendeur saisonnier", phrases: ["Disponible du [date] au [date], je suis motive et operationnel.", "Mon experience me permet d'etre autonome des les premiers jours.", "Dynamique et ponctuel, je m'adapte rapidement."], faq: [["Quand postuler ?", "Des mars-avril !"], ["Faut-il une vraie lettre ?", "Oui ! Cela vous demarque."], ["Comment postuler a 16 ans ?", "Avec une autorisation parentale."]], temoignage: { nom: "Lea S.", poste: "Job d'ete en restaurant", texte: "4 reponses positives sur 10 candidatures !" } },
  "candidature-spontanee": { t: "Candidature spontanee", s: "Tous secteurs", d: "Vous envoyez une candidature spontanee ? Notre IA redige une lettre qui capte l'attention.", c: "Montrez que vous connaissez l'entreprise et expliquez ce que vous pouvez apporter.", ex: "Candidature spontanee grande entreprise, PME, start-up", phrases: ["Votre entreprise m'inspire par [raison precise].", "Mes competences pourraient contribuer a [objectif].", "Je serais ravi d'echanger sur les opportunites."], faq: [["Ca marche ?", "Oui ! 70% des postes ne sont jamais publies."], ["Comment trouver le bon interlocuteur ?", "Cherchez sur LinkedIn."], ["Faut-il relancer ?", "Oui, 7 a 10 jours apres."]], temoignage: { nom: "Marc V.", poste: "Embauche chez Decathlon", texte: "Ma candidature spontanee a ete remarquee !" } },
  "serveur": { t: "Serveur / Serveuse", s: "Restauration", d: "Vous postulez comme serveur ? Notre IA genere une lettre qui met en valeur votre sens du service.", c: "Mettez en avant votre resistance au stress et votre polyvalence.", ex: "Serveur en restaurant, serveuse en brasserie, barman", phrases: ["Mon sourire et mon sens du service garantissent une experience client de qualite.", "Habitue au rythme soutenu, je reste efficace en rush.", "Ma connaissance des vins me permet de conseiller les clients."], faq: [["Faut-il de l'experience ?", "Pas toujours."], ["Quelles qualites ?", "Rapidite, sourire, resistance au stress."], ["Email ou manuscrit ?", "Email avec la lettre en piece jointe."]], temoignage: { nom: "Karim H.", poste: "Serveur en brasserie", texte: "Recrute en 48h !" } },
  "comptable": { t: "Comptable", s: "Finance et gestion", d: "Vous postulez comme comptable ? Notre IA cree une lettre technique.", c: "Mentionnez vos diplomes, logiciels maitrises et experience.", ex: "Comptable en cabinet, en entreprise, aide-comptable", phrases: ["Ma maitrise de Sage et Cegid garantit une gestion fiable.", "Rigoureux et methodique, j'assure le suivi dans les delais.", "Mon experience en cabinet m'a appris a gerer plusieurs dossiers."], faq: [["Quels logiciels ?", "Sage, Cegid, EBP, QuickBooks."], ["Le DCG est-il indispensable ?", "Le BTS CG suffit pour aide-comptable."], ["Comment se demarquer ?", "Mentionnez des resultats concrets."]], temoignage: { nom: "Claire M.", poste: "Comptable en cabinet", texte: "Exactement ce que les cabinets attendent !" } },
  "assistant-administratif": { t: "Assistant(e) administratif(ve)", s: "Administration", d: "Vous postulez comme assistant administratif ? Notre IA valorise votre organisation.", c: "Profils organises, autonomes et maitrisant le Pack Office.", ex: "Assistante de direction, assistant administratif, secretaire", phrases: ["Organisee et polyvalente, je gere efficacement les taches.", "Ma maitrise du Pack Office me rend operationnelle immediatement.", "Discrete et fiable, je suis le pilier de toute equipe."], faq: [["Quelles competences ?", "Organisation, Word/Excel, gestion d'agenda."], ["Faut-il des diplomes ?", "Un BTS SAM est un plus."], ["Comment se demarquer ?", "Montrez votre polyvalence."]], temoignage: { nom: "Sandrine T.", poste: "Assistante de direction", texte: "C'est la lettre qui l'a convaincu !" } },
  "developpeur": { t: "Developpeur / Developpeuse", s: "Informatique et tech", d: "Vous postulez comme developpeur ? Notre IA genere une lettre technique adaptee.", c: "Mentionnez vos langages, projets et veille technologique.", ex: "Developpeur web, mobile, full-stack, front-end", phrases: ["Passionne de code, je maitrise [langages].", "Mon approche clean code et agile sont des atouts.", "Mon GitHub actif temoigne de ma passion."], faq: [["Faut-il mentionner GitHub ?", "Oui !"], ["Lettre ou portfolio ?", "Les deux !"], ["Comment postuler en junior ?", "Projets personnels et curiosite."]], temoignage: { nom: "Maxime G.", poste: "Dev full-stack", texte: "Parfait pour la tech !" } },
  "agent-dentretien": { t: "Agent d'entretien", s: "Nettoyage et hygiene", d: "Vous postulez comme agent d'entretien ? Notre IA met en avant votre serieux.", c: "Fiabilite, ponctualite et techniques de nettoyage.", ex: "Agent d'entretien en entreprise, agent de proprete", phrases: ["Ponctuel et minutieux, j'assure un nettoyage impeccable.", "Mon experience m'a permis de maitriser les produits.", "Autonome et discret, je travaille efficacement."], faq: [["Faut-il une lettre ?", "Oui ! C'est un avantage."], ["Quelles qualites ?", "Ponctualite, serieux, discretion."], ["Faut-il des diplomes ?", "Non."]], temoignage: { nom: "Marie-Louise K.", poste: "Agent d'entretien", texte: "Choisie parmi 30 candidats !" } },
  "chauffeur-livreur": { t: "Chauffeur-livreur", s: "Transport et logistique", d: "Vous postulez comme chauffeur-livreur ? Notre IA met en avant votre permis et ponctualite.", c: "Type de permis, connaissance de la zone et experience.", ex: "Chauffeur-livreur, livreur de colis, chauffeur VTC", phrases: ["Titulaire du permis [type], je connais la region.", "Ponctuel et organise, je respecte les delais.", "Mon sens de l'orientation optimise mes tournees."], faq: [["Quel permis ?", "Permis B pour livraison legere."], ["Comment se demarquer ?", "Ponctualite et zero accident."], ["Mentionner son vehicule ?", "Si independant, oui."]], temoignage: { nom: "David R.", poste: "Livreur Chronopost", texte: "Simple et efficace !" } },
  "boulanger": { t: "Boulanger / Boulangere", s: "Artisanat", d: "Vous postulez comme boulanger ? Notre IA met en avant votre savoir-faire.", c: "Formation, techniques de panification et passion.", ex: "Boulanger artisanal, en grande surface, patissier-boulanger", phrases: ["Passionne par la panification, je maitrise le pain traditionnel.", "Matinal et rigoureux, habitue aux horaires decales.", "Mon CAP garantit un travail de qualite."], faq: [["Le CAP est obligatoire ?", "Fortement recommande."], ["Comment montrer sa passion ?", "Parlez de vos specialites."], ["Faut-il une lettre ?", "Oui, surtout en artisanal."]], temoignage: { nom: "Pierre B.", poste: "Boulanger artisanal", texte: "Mon patron a senti mon amour du metier !" } },
  "caissier": { t: "Caissier / Caissiere", s: "Commerce", d: "Vous postulez comme caissier ? Notre IA met en avant votre rigueur et sourire.", c: "Aisance avec la caisse, politesse et gestion des files.", ex: "Caissiere en supermarche, hotesse de caisse", phrases: ["Souriante et rapide, un passage en caisse agreable.", "Rigueur irreprochable dans la manipulation des fonds.", "Polyvalente, je peux aussi faire la mise en rayon."], faq: [["Experience necessaire ?", "Non."], ["Quelles qualites ?", "Rapidite, sourire, precision."], ["Sans diplome ?", "Oui, poste accessible."]], temoignage: { nom: "Amina F.", poste: "Caissiere Carrefour", texte: "Premier emploi decroche !" } },
  "cuisinier": { t: "Cuisinier / Cuisiniere", s: "Restauration", d: "Vous postulez comme cuisinier ? Notre IA met en valeur votre creativite culinaire.", c: "Specialites, formation et capacite sous pression.", ex: "Cuisinier en restaurant, chef de partie, commis", phrases: ["Forme en cuisine traditionnelle, je maitrise les techniques.", "Creatif et organise, je gere un service de [X] couverts.", "Mon experience en brigade m'a appris la rigueur."], faq: [["CAP necessaire ?", "Recommande."], ["Montrer sa creativite ?", "Mentionnez un plat signature."], ["Le secteur recrute ?", "Oui, forte tension."]], temoignage: { nom: "Antoine C.", poste: "Chef de partie", texte: "Recrute dans un restaurant etoile !" } },
  "educateur-specialise": { t: "Educateur specialise", s: "Social et educatif", d: "Vous postulez comme educateur specialise ? Notre IA adapte au secteur social.", c: "Diplome DEES, stages et accompagnement de publics en difficulte.", ex: "Educateur en foyer, de rue, PJJ, moniteur-educateur", phrases: ["Mon DEES m'a prepare a accompagner des publics vulnerables.", "Empathique et patient, je sais etablir la confiance.", "Mon experience m'a appris a adapter mes interventions."], faq: [["Le DEES est obligatoire ?", "Oui."], ["Comment parler de sa motivation ?", "Racontez une experience."], ["Quel type de lettre ?", "Sincere et engagee."]], temoignage: { nom: "Youssuf O.", poste: "Educateur en foyer", texte: "Mon engagement social parfaitement traduit." } },
  "electricien": { t: "Electricien", s: "BTP et artisanat", d: "Vous postulez comme electricien ? Notre IA met en avant vos habilitations.", c: "Habilitations electriques, CAP/BEP et experience.", ex: "Electricien du batiment, industriel", phrases: ["Titulaire des habilitations BR, B1V et B2V.", "Mon CAP et mes [X] ans me rendent autonome.", "Je maitrise les installations domestiques et industrielles."], faq: [["Habilitations obligatoires ?", "Oui."], ["Diplome ?", "CAP electricien minimum."], ["Se demarquer ?", "Specialites : domotique, solaire, fibre."]], temoignage: { nom: "Julien M.", poste: "Electricien du batiment", texte: "Embauche en CDI !" } },
  "hotesse-daccueil": { t: "Hotesse d'accueil", s: "Accueil", d: "Vous postulez comme hotesse d'accueil ? Notre IA met en avant votre presentation.", c: "Presentation, langues et sens du service.", ex: "Hotesse en entreprise, evenementiel, standardiste", phrases: ["Presentation soignee et sourire naturel.", "Bilingue, a l'aise avec la clientele internationale.", "Gestion des situations delicates avec diplomatie."], faq: [["Parler anglais ?", "Gros plus."], ["Experience indispensable ?", "Non."], ["Tenue ?", "Professionnelle."]], temoignage: { nom: "Charlotte L.", poste: "Hotesse LVMH", texte: "Elegante et professionnelle !" } },
  "ingenieur": { t: "Ingenieur", s: "Ingenierie", d: "Vous postulez comme ingenieur ? Notre IA genere une lettre professionnelle.", c: "Ecole, projets techniques et resolution de problemes.", ex: "Ingenieur informatique, mecanique, civil", phrases: ["Diplome de [ecole], expertise en [domaine].", "Approche analytique et rigueur scientifique.", "Mon experience sur le projet [nom] a developpe mes competences."], faq: [["Mentionner son ecole ?", "Oui, important en France."], ["Valoriser ses projets ?", "Decrivez role et resultats."], ["Technique ou general ?", "Mix des deux."]], temoignage: { nom: "Alexandre D.", poste: "Ingenieur Airbus", texte: "Bon equilibre technique et personnalite." } },
  "manutentionnaire": { t: "Manutentionnaire", s: "Logistique", d: "Vous postulez comme manutentionnaire ? Notre IA met en avant votre endurance.", c: "CACES, experience en entrepot et rigueur.", ex: "Manutentionnaire en entrepot, cariste, magasinier", phrases: ["Titulaire du CACES, je maitrise les chariots elevateurs.", "Endurant et rigoureux, je respecte la securite.", "Mon experience m'a rendu rapide et efficace."], faq: [["CACES obligatoire ?", "Pas toujours, mais gros plus."], ["Faut-il une lettre ?", "Oui, peu de candidats en envoient."], ["Quelles qualites ?", "Endurance, ponctualite, rigueur."]], temoignage: { nom: "Ibrahima S.", poste: "Manutentionnaire Amazon", texte: "Rappele le jour meme !" } },
  "mecanicien": { t: "Mecanicien / Mecanicienne", s: "Automobile", d: "Vous postulez comme mecanicien ? Notre IA redige une lettre technique.", c: "Certifications, marques maitrisees et diagnostic.", ex: "Mecanicien automobile, poids lourd, moto", phrases: ["Maitrise du diagnostic electronique.", "Forme sur les vehicules [marques].", "Passionne d'automobile."], faq: [["Certifications ?", "CAP, BAC pro, certifications constructeurs."], ["Se demarquer ?", "Specialites : hybride, electrique."], ["Secteur recrute ?", "Oui, metier en tension."]], temoignage: { nom: "Kevin P.", poste: "Mecanicien Renault", texte: "En poste depuis 6 mois !" } },
  "pharmacien": { t: "Pharmacien / Pharmacienne", s: "Sante", d: "Vous postulez comme pharmacien ? Notre IA adapte au secteur pharmaceutique.", c: "Diplome, stages officinaux et conseil patient.", ex: "Pharmacien d'officine, hospitalier, en industrie", phrases: ["Docteur en pharmacie, expertise en conseil.", "Rigueur dans la delivrance des medicaments.", "Ecoute et adaptation des conseils."], faq: [["Doctorat indispensable ?", "Oui pour pharmacien."], ["Se demarquer ?", "Vos specialites."], ["Officines recrutent ?", "Oui."]], temoignage: { nom: "Sophie R.", poste: "Pharmacienne adjointe", texte: "Recrutee dans ma pharmacie preferee !" } },
  "plombier": { t: "Plombier", s: "BTP", d: "Vous postulez comme plombier ? Notre IA met en avant votre savoir-faire.", c: "Qualifications, depannage et autonomie.", ex: "Plombier chauffagiste, sanitaire, depanneur", phrases: ["Mon CAP et mes [X] ans font de moi un plombier qualifie.", "Autonome et reactif en depannage et installation.", "Maitrise des normes DTU."], faq: [["Qualifications ?", "CAP installateur sanitaire minimum."], ["Faut-il une lettre ?", "Oui en entreprise structuree."], ["Se demarquer ?", "Specialites : pompe a chaleur, solaire."]], temoignage: { nom: "Christophe N.", poste: "Plombier chauffagiste", texte: "CDI chez un grand groupe BTP !" } },
  "professeur": { t: "Professeur / Enseignant", s: "Education", d: "Vous postulez comme professeur ? Notre IA met en valeur votre pedagogie.", c: "Approche pedagogique, diplomes et adaptabilite.", ex: "Professeur des ecoles, de maths, contractuel, formateur", phrases: ["Ma passion pour la transmission guide mon enseignement.", "J'adapte mes methodes aux besoins de chaque eleve.", "Mon approche innovante favorise l'engagement."], faq: [["CAPES obligatoire ?", "Pour titulaire oui. Master suffit pour contractuel."], ["Se demarquer ?", "Approche pedagogique concrete."], ["Les lettres comptent ?", "Oui, surtout pour contractuels."]], temoignage: { nom: "Camille J.", poste: "Professeure de francais", texte: "Le principal a ete convaincu !" } },
  "secretaire": { t: "Secretaire", s: "Administration", d: "Vous postulez comme secretaire ? Notre IA met en avant votre organisation.", c: "Word, Excel, rapidite de frappe et confidentialite.", ex: "Secretaire medicale, juridique, de direction", phrases: ["Maitrise des outils bureautiques et rapidite de frappe.", "Discrete et organisee, gestion des agendas avec precision.", "Proactive et anticipation des besoins."], faq: [["Quels logiciels ?", "Word, Excel, PowerPoint, Outlook."], ["Diplome ?", "BTS SAM recommande."], ["Se demarquer ?", "Rapidite de frappe et discretion."]], temoignage: { nom: "Valerie G.", poste: "Secretaire medicale", texte: "Embauchee dans le cabinet de mes reves !" } },
  "technicien-informatique": { t: "Technicien informatique", s: "Informatique", d: "Vous postulez comme technicien informatique ? Notre IA met en avant vos competences.", c: "Certifications, helpdesk et maitrise des systemes.", ex: "Technicien helpdesk, reseau, systemes, support IT", phrases: ["Certifie [certification], je resous les incidents niveau 1 a 3.", "Patience et pedagogie avec les utilisateurs.", "Maitrise Windows Server, Linux et TCP/IP."], faq: [["Certifications ?", "CompTIA A+, ITIL, Microsoft, Cisco."], ["Experience prime ?", "Oui en informatique."], ["Montrer sa valeur ?", "Nombre de tickets resolus."]], temoignage: { nom: "Romain F.", poste: "Technicien helpdesk", texte: "Recrute en ESN !" } },
  "agent-immobilier": { t: "Agent immobilier", s: "Immobilier", d: "Vous postulez comme agent immobilier ? Notre IA redige une lettre commerciale.", c: "Marche local, reseau et resultats de vente.", ex: "Agent en agence, negociateur, mandataire", phrases: ["Connaissance approfondie du marche local.", "[X] transactions pour [X] millions.", "Reseau et techniques de negociation."], faq: [["Carte pro obligatoire ?", "Pour independant oui."], ["Se demarquer ?", "Chiffrez vos resultats."], ["Marche recrute ?", "Oui, profils commerciaux."]], temoignage: { nom: "Stephanie W.", poste: "Negociatrice", texte: "Rappelee dans l'heure !" } },
  "animateur": { t: "Animateur / Animatrice", s: "Animation", d: "Vous postulez comme animateur ? Notre IA genere une lettre dynamique.", c: "BAFA, experiences et encadrement de groupes.", ex: "Animateur centre de loisirs, colonie, sportif", phrases: ["Titulaire du BAFA, j'ai encadre [X] enfants.", "Creatif et dynamique, activites adaptees.", "Bonne humeur contagieuse."], faq: [["BAFA obligatoire ?", "Tres recommande."], ["Se demarquer ?", "Specialites."], ["Sans experience ?", "Avec BAFA et motivation, oui."]], temoignage: { nom: "Hugo T.", poste: "Animateur en colonie", texte: "Pris tout de suite !" } },
  "auxiliaire-de-vie": { t: "Auxiliaire de vie", s: "Aide a la personne", d: "Vous postulez comme auxiliaire de vie ? Notre IA redige une lettre humaine.", c: "Diplome, experience et patience.", ex: "Auxiliaire de vie a domicile, aide a domicile", phrases: ["Mon DEAVS et mes [X] ans m'ont appris a accompagner avec respect.", "Patiente et attentionnee.", "Maintenir l'autonomie et le bien-etre."], faq: [["Diplome ?", "DEAVS ou ADVF recommande."], ["Montrer son empathie ?", "Racontez une experience."], ["Secteur recrute ?", "Enormement !"]], temoignage: { nom: "Patricia M.", poste: "Auxiliaire de vie", texte: "Mon coeur et professionnalisme bien montres." } },
  "coiffeur": { t: "Coiffeur / Coiffeuse", s: "Beaute", d: "Vous postulez comme coiffeur ? Notre IA genere une lettre creative.", c: "CAP/BP coiffure, specialites et conseil client.", ex: "Coiffeuse en salon, barbier, coloriste", phrases: ["Passionnee, je maitrise coupe, coloration et coiffage.", "Sens artistique et ecoute pour sublimer chaque client.", "Formee aux dernieres tendances."], faq: [["CAP obligatoire ?", "Oui pour salarie."], ["Se demarquer ?", "Realisations et specialites."], ["Secteur recrute ?", "Oui, coloristes et barbiers."]], temoignage: { nom: "Melissa A.", poste: "Coiffeuse coloriste", texte: "Salon de mes reves !" } },
  "gestionnaire-de-paie": { t: "Gestionnaire de paie", s: "RH", d: "Vous postulez comme gestionnaire de paie ? Notre IA redige une lettre technique.", c: "Logiciels de paie, droit social et precision.", ex: "Gestionnaire de paie en cabinet, en entreprise", phrases: ["Maitrise de Sage, Cegid et Silae.", "Rigoureux et a jour sur les evolutions legales.", "Experience avec des conventions collectives variees."], faq: [["Quels logiciels ?", "Sage, Cegid, Silae, ADP, DSN."], ["Droit social ?", "Essentiel."], ["Evoluer ?", "Vers responsable paie ou RH."]], temoignage: { nom: "Aurelie P.", poste: "Gestionnaire de paie", texte: "Recrutee en grand cabinet !" } },
  "graphiste": { t: "Graphiste / Designer", s: "Creation", d: "Vous postulez comme graphiste ? Notre IA genere une lettre creative.", c: "Portfolio, outils et projets marquants.", ex: "Graphiste freelance, directeur artistique, UX designer", phrases: ["Creativite et efficacite au service de votre communication.", "Suite Adobe, Figma et prototypage UX.", "Realisations avec resultats mesurables."], faq: [["Portfolio indispensable ?", "Absolument !"], ["Diplome ?", "Le portfolio prime."], ["Lettre creative ou classique ?", "Professionnel avec personnalite."]], temoignage: { nom: "Quentin B.", poste: "Graphiste en agence", texte: "La lettre a complete mon portfolio !" } },
  "preparateur-de-commandes": { t: "Preparateur de commandes", s: "Logistique", d: "Vous postulez comme preparateur de commandes ? Notre IA met en avant votre rapidite.", c: "CACES, experience en entrepot et precision.", ex: "Preparateur en entrepot, picker, agent logistique", phrases: ["Rapide et precis, [X] commandes par heure.", "Titulaire du CACES, autonome en entrepot.", "Organisation pour respecter les delais."], faq: [["CACES necessaire ?", "Pas toujours, mais avantage."], ["Experience ?", "Postes ouverts aux debutants."], ["Se demarquer ?", "Rapidite et faible taux d'erreur."]], temoignage: { nom: "Moussa D.", poste: "Preparateur Amazon", texte: "Selectionne parmi 50 candidats !" } },
  "receptionniste": { t: "Receptionniste", s: "Hotellerie", d: "Vous postulez comme receptionniste ? Notre IA met en avant votre accueil et langues.", c: "Bilingue, souriant et logiciels de reservation.", ex: "Receptionniste d'hotel, night auditor, concierge", phrases: ["Bilingue, accueil professionnel des clients internationaux.", "Maitrise de Opera et Mews.", "Sourire et disponibilite pour un accueil chaleureux."], faq: [["Combien de langues ?", "Deux minimum."], ["Diplome hotelier ?", "Un plus, mais experience suffit."], ["Horaires ?", "Decales, week-ends et jours feries."]], temoignage: { nom: "Olga S.", poste: "Receptionniste Marriott", texte: "Directeur impressionne !" } },
  "responsable-marketing": { t: "Responsable marketing", s: "Marketing", d: "Vous postulez comme responsable marketing ? Notre IA genere une lettre strategique.", c: "Resultats chiffres et competences digitales.", ex: "Responsable marketing digital, brand manager, growth", phrases: ["Strategie generant [X]% de croissance.", "Expert Google Ads et Meta Ads.", "Approche data-driven."], faq: [["Chiffrer ?", "Absolument."], ["Outils ?", "Google Analytics, HubSpot, SEMrush."], ["Se demarquer ?", "Campagne concrete avec resultats."]], temoignage: { nom: "Laura V.", poste: "Responsable marketing", texte: "Recrutee en scale-up !" } },
  "technicien-de-maintenance": { t: "Technicien de maintenance", s: "Industrie", d: "Vous postulez comme technicien de maintenance ? Notre IA redige une lettre technique.", c: "Habilitations et competences en mecanique, electrique et automatisme.", ex: "Technicien maintenance industrielle, SAV, CVC", phrases: ["Polyvalent en mecanique, electrique et pneumatique.", "Maintenance preventive reduisant les pannes de [X]%.", "Diagnostic et reparation rapides."], faq: [["Competences ?", "Electricite, mecanique, automatisme."], ["Habilitations ?", "Electriques quasi obligatoires."], ["Secteur recrute ?", "Un des plus en tension !"]], temoignage: { nom: "Nicolas H.", poste: "Technicien maintenance", texte: "CDI signe !" } },
  "parcoursup": { t: "Parcoursup", s: "Orientation post-bac", d: "Vous redigez votre lettre Parcoursup ? Notre IA formule un projet convaincant.", c: "Projet professionnel, pourquoi cette formation et resultats scolaires.", ex: "Licence de droit, BTS, classe preparatoire, PASS medecine", phrases: ["Mon projet s'inscrit dans votre formation.", "Mes resultats temoignent de ma motivation.", "Votre formation est l'etape essentielle vers mon objectif."], faq: [["Combien de caracteres ?", "1500 maximum."], ["Personnaliser ?", "Oui, absolument !"], ["Sans projet precis ?", "Expliquez ce qui vous attire."]], temoignage: { nom: "Ines C.", poste: "Admise en licence de droit", texte: "Acceptee dans mon premier voeu !" } },
};

const SITE = "https://lettredemotivation-ia.fr";

export async function getStaticPaths() {
  return { paths: Object.keys(M).map(s => ({ params: { metier: `lettre-de-motivation-${s}` } })), fallback: false };
}

export async function getStaticProps({ params }) {
  const slug = params.metier.replace("lettre-de-motivation-", "");
  const data = M[slug] || null;
  if (!data) return { notFound: true };
  return { props: { slug, ...data } };
}

export default function MetierPage({ slug, t, s, d, c, ex, phrases, faq, temoignage }) {
  const url = `${SITE}/lettre-de-motivation-${slug}`;

  return (
    <div style={{ fontFamily: sans, color: T.text, minHeight: "100vh", background: T.bg }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&display=swap');*{box-sizing:border-box}a{text-decoration:none}`}</style>
      <Head>
        <title>{`Lettre de motivation ${t} - Generateur IA gratuit`}</title>
        <meta name="description" content={d} />
        <meta property="og:title" content={`Lettre de motivation ${t} - IA gratuit`} />
        <meta property="og:description" content={d} />
        <meta property="og:url" content={url} />
        <link rel="canonical" href={url} />
      </Head>

      {/* NAV */}
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", paddingTop: 24, paddingBottom: 20 }}>
          <a href="/" style={{ fontSize: 15, fontWeight: 700, color: T.text }}>
            lettredemotivation-<span style={{ background: "linear-gradient(135deg, #059669, #2563eb)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>ia.fr</span>
          </a>
          <a href="/" style={{ fontSize: 12, fontWeight: 600, color: T.accent, padding: "8px 18px", borderRadius: 20, background: T.greenSoft, border: `1px solid ${T.accentBorder}` }}>
            Creer ma lettre de motivation
          </a>
        </div>
      </div>

      {/* HERO */}
      <div style={{ background: "linear-gradient(135deg, rgba(5,150,105,0.04), rgba(37,99,235,0.04))", padding: "48px 0 56px", borderTop: `1px solid ${T.border}`, borderBottom: `1px solid ${T.border}` }}>
        <div style={{ maxWidth: 720, margin: "0 auto", padding: "0 24px" }}>
          <div style={{ fontSize: 11, fontWeight: 600, color: T.accent, textTransform: "uppercase", letterSpacing: 2, marginBottom: 12 }}>{s}</div>
          <h1 style={{ fontSize: 32, fontWeight: 800, color: T.text, lineHeight: 1.2, marginBottom: 16 }}>
            Lettre de motivation <span style={{ background: "linear-gradient(135deg, #059669, #2563eb)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>{t}</span>
          </h1>
          <p style={{ fontSize: 16, color: T.textMuted, lineHeight: 1.7, maxWidth: 560, marginBottom: 28 }}>{d}</p>
          <a href="/" style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "14px 28px", borderRadius: 10, background: "linear-gradient(135deg, #059669, #047857)", color: "#fff", fontWeight: 600, fontSize: 14, boxShadow: "0 4px 16px rgba(5,150,105,0.25)" }}>
            Generer ma lettre de motivation {t.toLowerCase()} →
          </a>
        </div>
      </div>

      {/* CONTENU */}
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px 0" }}>
        <h2 style={{ fontSize: 20, fontWeight: 700, color: T.text, marginBottom: 12 }}>Nos conseils pour votre lettre de motivation {t.toLowerCase()}</h2>
        <p style={{ fontSize: 14, color: T.textMuted, lineHeight: 1.8, marginBottom: 32 }}>{c}</p>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: T.text, marginBottom: 12 }}>Exemples de phrases pour votre lettre de motivation</h3>
        <div style={{ display: "flex", flexDirection: "column", gap: 10, marginBottom: 40 }}>
          {phrases.map((p, i) => (
            <div key={i} style={{ padding: "14px 18px", borderRadius: 10, background: T.greenSoft, border: `1px solid ${T.accentBorder}`, fontSize: 13, color: T.text, lineHeight: 1.6, fontStyle: "italic" }}>
              &ldquo;{p}&rdquo;
            </div>
          ))}
        </div>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: T.text, marginBottom: 12 }}>Types de postes couverts</h3>
        <p style={{ fontSize: 14, color: T.textMuted, lineHeight: 1.8, marginBottom: 40 }}>{ex}</p>

        <h2 style={{ fontSize: 20, fontWeight: 700, color: T.text, marginBottom: 16 }}>Questions frequentes</h2>
        <div style={{ display: "flex", flexDirection: "column", gap: 16, marginBottom: 40 }}>
          {faq.map(([q, a], i) => (
            <div key={i} style={{ padding: "18px 20px", borderRadius: 12, background: "#f8fafc", border: `1px solid ${T.border}` }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: T.text, marginBottom: 6 }}>{q}</div>
              <div style={{ fontSize: 13, color: T.textMuted, lineHeight: 1.7 }}>{a}</div>
            </div>
          ))}
        </div>

        {temoignage && (
          <div style={{ padding: "24px", borderRadius: 14, background: T.blueSoft, border: `1px solid ${T.blueBorder}`, marginBottom: 40 }}>
            <p style={{ fontSize: 14, color: T.text, lineHeight: 1.7, fontStyle: "italic", marginBottom: 10 }}>&ldquo;{temoignage.texte}&rdquo;</p>
            <p style={{ fontSize: 12, color: T.blue, fontWeight: 600 }}>{temoignage.nom} — {temoignage.poste}</p>
          </div>
        )}

        <div style={{ textAlign: "center", padding: "40px 0 24px", borderTop: `1px solid ${T.border}` }}>
          <h2 style={{ fontSize: 22, fontWeight: 800, color: T.text, marginBottom: 10 }}>
            Pret a creer votre lettre de motivation {t.toLowerCase()} ?
          </h2>
          <p style={{ fontSize: 14, color: T.textMuted, marginBottom: 24, lineHeight: 1.6 }}>
            2 lettres de motivation gratuites, aucune carte bancaire requise.
          </p>
          <a href="/" style={{ display: "inline-flex", padding: "16px 36px", borderRadius: 10, background: "linear-gradient(135deg, #059669, #047857)", color: "#fff", fontWeight: 700, fontSize: 15, boxShadow: "0 4px 16px rgba(5,150,105,0.25)" }}>
            Generer ma lettre de motivation maintenant
          </a>
        </div>

        <div style={{ padding: "20px 0", textAlign: "center", borderTop: `1px solid ${T.border}`, marginTop: 16 }}>
          <p style={{ fontSize: 12, color: T.textMuted, marginBottom: 8, fontWeight: 500 }}>
            Postulez sur : <a href="https://www.indeed.fr" target="_blank" rel="noopener noreferrer" style={{ color: T.blue, fontWeight: 600 }}>Indeed</a> · <a href="https://www.hellowork.com" target="_blank" rel="noopener noreferrer" style={{ color: T.blue, fontWeight: 600 }}>HelloWork</a> · <a href="https://www.linkedin.com/jobs" target="_blank" rel="noopener noreferrer" style={{ color: T.blue, fontWeight: 600 }}>LinkedIn</a> · <a href="https://www.francetravail.fr" target="_blank" rel="noopener noreferrer" style={{ color: T.blue, fontWeight: 600 }}>France Travail</a>
          </p>
          <p style={{ fontSize: 11, color: T.textDim, fontWeight: 500 }}>
            <a href="/mentions-legales" style={{ color: T.textDim }}>Mentions legales</a> · <a href="mailto:Melomel.paris@gmail.com" style={{ color: T.textDim }}>Contact</a>
          </p>
        </div>
      </div>
    </div>
  );
}
